### ISSUE TITLE
[Question]: How to export to juicer (.hic)

### ISSUE THREAD

**Issue by malszycki** [epi2me-labs/wf-pore-c#15]
### What happened?

Hi. The output seems to be badly formatted for juicer_tools pre. The order of sorted pairs file is wrong. In my case it results in:
.........................Error: the chromosome combination 1_10 appears in multiple blocks

Since the SnakePipes version had working juicer export. Could you share the code that was formatting the pairs, so it would fit the juicer_tools pre?

Sorry for posting as a bug, but there's no other option.

### Operating System

Windows 10

### Workflow Execution

Command line

### Workflow Execution - CLI Execution Profile

None

### Workflow Version

wf-pore-c v0.0.7-g68cf804

### Relevant log output

```shell
$ java -Xmx8g -jar ../juicer_scripts/common/juicer_tools.jar pre \
>     ../data/wt.nodups.sorted.pairs.gz \
>     wt.hic \
>     t2t-chm13-v1.1.chrom.sizes
Not including fragment map
Start preprocess
Writing header
Writing body
.........................Error: the chromosome combination 1_10 appears in multiple blocks
```

**Comment by Oksanak22** [comment]
Hello!
Are there any updates on how to get the output file that can works with juicer?
Thank you.

**Comment by sarahjeeeze** [comment]
Hi, this should now be avaiable using the `--hi_c` parameter

**Comment by Oksanak22** [comment]
Thank you for this update. Could you please point me to where I have to add this parameter?

**Comment by tinyfallen** [comment]
> Hi, this should now be avaiable using the `--hi_c` parameter

Hi @sarahjeeeze,

Thanks for the great tool!

When I added **--hi_c** option like this

**"nextflow run epi2me-labs/wf-pore-c --fastq /data2/home/ydn/yty/rawdata/pame/pore-c/pass.fq.gz --sample porec --ref ref.fa --cutter 'DpnII' --out_dir out --threads 48 --digest_annotate_threads 48 --mcool --paired_end --hi_c"** 

it terminated with 

**"Access to 'merge_pairs.out' is undefined since the process 'merge_pairs' has not been invoked before accessing the output attribute**

**-- Check script '/export/home/ydn/.nextflow/assets/epi2me-labs/wf-pore-c/main.nf' at line: 319 or see '.nextflow.log' file for more details"**

And after I excuted the command, pressing backspace on keyboard will show ^H in the CLI and did not delete anything. 

Could you please give me some advices? 

Best regard!

**Comment by tinyfallen** [comment]
I coincidentally found that --hi_c should appear with --pairs! My pipeline now is running and I am wishing it success~

**Comment by sarahjeeeze** [comment]
@Oksanak22 Add it at the end of the existing command or if you are running it in the EPI2ME application it is an option in the `output_options` tab and as mentioned you will need to also select the pair parameter for now in `4dn_files_options`

**Comment by tinyfallen** [comment]
> Hi, thanks for this feedback, this is an oversite. I will update the workflow to ensure the pairs file is create if --hi_c parameter is used. Will let you know when this is released.

Thanks for your work! My first purpose is to get an editabe .hic file with juicebox and I made some effort to convert the pairs file to merged_nodups style in 3D-DNA pipeline to correct my assembly. 

As far as I know, there is only the juicebox which allows users to expediently rearrange the contigs by Hi-C or pore-C, and the related tools are all tailored for paired-end Hi-C data until now. So I prefer .hic format for contact signal storage~

Best regards.

**Comment by sarahjeeeze** [comment]
Hi, @Oksanak22 it would be good to know what the error was for the failed run?

**Comment by Oksanak22** [comment]
Hi, @sarahjeeeze.
Here is the error.
[slurm-39950425.txt](https://github.com/epi2me-labs/wf-pore-c/files/12465869/slurm-39950425.txt). And it generated just "execution" folder with "trace.txt" file.

**Comment by sarahjeeeze** [comment]
@Oksanak22 I think currently you also need to add the `--pairs` parameter, let me know how that goes or share the log.

**Comment by sarahjeeeze** [comment]
Not sure as the what looks to me like a truncacted `nextflow.log` file is not something I have seen before. It could be something to do with the environment you are running it on/the cluster. You may need to reach out to your system admins. Did you try it more than once? The command looks okay.

**Comment by Oksanak22** [comment]
@sarahjeeeze yes, I tried several times. Now it has been running for more than 6h and I just got "execution" folder in an output data folder.

**Comment by sarahjeeeze** [comment]
6hours sounds plausible, it can take a while on a large dataset. What additional compute are you giving it in your config file? If you are processing a large data set its a good idea to set it higher than the default, and as mentioned in the schema are you increasing the various threads parameters to the recommended values? could you send an updated .log file ?

**Comment by Oksanak22** [comment]
Hello.
Here it is
[nextflow.log.txt](https://github.com/epi2me-labs/wf-pore-c/files/12499341/nextflow.log.txt)

**Comment by sarahjeeeze** [comment]
What about the additional config file you are using?

**Comment by Oksanak22** [comment]
Here it is:
[nextflow.config.txt](https://github.com/epi2me-labs/wf-pore-c/files/12500117/nextflow.config.txt)

**Comment by sarahjeeeze** [comment]
I would recommend increasing cpus to 16 and other threads parameters to - as suggested in the parameters help text. If it still doesn't work probably contact your system admin to see if the slurm config settings are correct.  
```
ubam_map_threads = 12
digest_annotate_threads = 2
ubam_bam2fq_threads = 1
```

**Comment by sarahjeeeze** [comment]
Closing through lack of response.
