### ISSUE TITLE
[Bug]: digest_align_annotate failed on large pore-c data

### ISSUE THREAD

**Issue by divinomas** [epi2me-labs/wf-pore-c#16]
### What happened?

I have a large pore-c data to analysis (156 Gb in fastq.gz) on a server with 150+ cpu threads and 1 Tb memory. 
I have tried several threading parameters:  [--threads 150 --ubam_map_threads 150 --digest_annotate_threads 25 --ubam_bam2fq_threads 150] or setting digest_annotate_threads to be 1, 5 or 10.
However, all tries failed on the digest_align_annotate step, with the xxx.ns.bam file showing "[W::bgzf_read_block] EOF marker is absent" error.
Another try with --chunk_size 50000 or 1000000 tested following the suggestions in https://github.com/epi2me-labs/wf-pore-c/issues/12. This try failed either with the system run out of memory.
Any suggestion on this issue?

### Operating System

ubuntu 20.04

### Workflow Execution

Command line

### Workflow Execution - EPI2ME Labs Versions

wf-pore-c v0.0.5-gd613498

### Workflow Execution - CLI Execution Profile

Docker

### Workflow Version

nextflow version 23.04.1

### Relevant log output

```shell
[W::bgzf_read_block] EOF marker is absent
```

**Comment by sarahjeeeze** [comment]
Hi, We have run it on a few data sets of that size and found it usually takes a few hours if you set it to the recommended values of `--threads 4 --ubam_map_threads 12 --digest_annotate_threads 2 --ubam_bam2fq_threads 1`
Did you also ammend the executor section in `nextflow.config` file to match the resources you are providing?, you can  provide this in an additional file to the `-c` parameter. See https://www.nextflow.io/docs/latest/config.html for more info

```executor {
    $local {
        cpus = 32
        memory = " 80GB"
    }
}
```

**Comment by divinomas** [comment]
Hi @sarahjeeeze 
I have tried your thread and nextflow.config settings, but it still reported "EOF marker is absent" error.
At last, I found setting chunk_size to 7000000 works on my server.

Another issue remains:
The chromunity dir contains separated chromunity files for each chunk.
Thanks.

**Comment by divinomas** [comment]
Hi, @sarahjeeeze . Thanks.
I tried your thread and nextflow.config settings, it still reported the "EOF marker is absent" error.
Retry with the chunk-size set to 7000000 works on my node.

**Comment by divinomas** [comment]
Hi, @sarahjeeeze . Thanks.
I have tried your thread and nextflow.config settings, but the pipeline still reported the "EOF marker is absent" error.
Set chunk-size to 7000000 solved my problem. 

Two issues found after digest_align_annotate:
1. pairsToCooler failed. The error message is "TypeError: 'IOHandles' object is not subscriptable", from the command "cooler cload pairs -c1 2 -p1 3 -c2 4 -p2 5 ... ...". However, when I tested the same pairs.gz file with a local cooler binary but not the cooler from the docker image, it works fine. 
2. merge_parquets_to_dataset didn't merge actually, parquet file for each chunk was just copied.

**Comment by sarahjeeeze** [comment]
Hi, thanks for the feedback. Are you still working on version 0.0.5 as mentioned above? Perhaps update to the latest version 0.0.8. I seem to remember that pairs to coolers error from a previous version. Thanks for the second point, we will look in to updating this step to actually merge the files.

**Comment by divinomas** [comment]
pairsToCooler works on 0.0.8. Thanks.

**Comment by sarahjeeeze** [comment]
Closing at this is resolved.
