### ISSUE TITLE
[Bug]: fastcat: command not found when running with apptainer

### ISSUE THREAD

**Issue by katsikora** [epi2me-labs/wf-pore-c#17]
### What happened?

I ran the pore-C nextflow workflow test command with apptainer and on a slurm cluster. Workflow failed with the error:  fastcat: command not found.

PS: I'm on CentOS, but this option is missing from the pull down menu.
PS2: I'm running the workflow with apptainer, not singularity as specified below.

### Operating System

ubuntu 20.04

### Workflow Execution

Command line

### Workflow Execution - CLI Execution Profile

Singularity

### Workflow Version

wf-pore-c-0.0.8

### Relevant log output

```shell
--------------------------------------------------------------------------------
This is epi2me-labs/wf-pore-c v0.0.8-gba50dfd.
--------------------------------------------------------------------------------
WARN: Nextflow version 22.10.7 does not match workflow required version: >=22.10.8 -- Execution will continue, but things may break!
WARN: Access to undefined parameter `sample` -- Initialise it to a default value eg. `params.sample = some_value`
Checking fastq input.
executor >  slurm (4)
[71/f34398] process > POREC:fastcat (1)                      [  0%] 0 of 1
[-        ] process > POREC:index_ubam                       -
[82/cb2a8a] process > POREC:prepare_genome:index_ref_mmi (1) [  0%] 0 of 1
[-        ] process > POREC:digest_align_annotate            -
[-        ] process > POREC:haplotag_alignments              -
[-        ] process > POREC:merge_coordsorted_bams           -
[-        ] process > POREC:merge_namesorted_bams            -
[-        ] process > POREC:create_restriction_bed           -
[-        ] process > POREC:to_pairs_file                    -
[-        ] process > POREC:pairsToCooler                    -
[-        ] process > POREC:merge_mcools                     -
[-        ] process > POREC:merge_pairs                      -
[-        ] process > POREC:merge_pairs_stats                -
[-        ] process > POREC:pair_stats_report                -
[-        ] process > POREC:merge_parquets_to_dataset        -
[-        ] process > POREC:merge_paired_end_bams            -
[f6/52071f] process > POREC:getVersions                      [100%] 1 of 1, failed: 1 ✘
[cb/4a8de2] process > POREC:getParams                        [  0%] 0 of 1
[-        ] process > POREC:makeReport                       -
Error executing process > 'POREC:getVersions'

Caused by:
  Process `POREC:getVersions` terminated with an error exit status (127)

Command executed:

  fastcat --version | sed 's/^/fastcat,/' >> versions.txt
  mosdepth --version | sed 's/ /,/' >> versions.txt
  pairtools --version | sed 's/\<version\>//g' >> versions.txt
  whatshap --version | sed 's/^/whatshap,/' >> versions.txt
  pore-c-py --version | sed 's/ /,/' >> versions.txt
  samtools --version | (head -n 1 && exit 0) | sed 's/ /,/' >> versions.txt

Command exit status:
  127

Command output:
  (empty)

Command error:
  .command.sh: line 2: fastcat: command not found

Work dir:
  /raven/ptmp/kasik/software/wf-pore-c-0.0.8/work/f6/52071f9fda6d321a905f56f105058a

Tip: you can replicate the issue by changing to the process work dir and entering the command `bash .command.run`


WARN: Killing running tasks (3)
```

**Comment by sarahjeeeze** [comment]
Hi, Thanks for the feedback. Could you give more details, what was the full cmd used? - for apptainer the `-profile singularity` parameter should work. I think nextflow also needs to be updated to the latest version with `nextflow self-update`.

**Comment by katsikora** [comment]
Hi, thanks for responding.
I've added an `apptainer` profile to the config that works with our slurm cluster. The `singularity` profile wasn't working out of the box.

I've solved the issue by passing setting the NXF_SINGULARITY_CACHEDIR variable in my .bash_profile to a path that the worker nodes can see. I guess the issue was cluster environment related. Would you like to add this as an option to the issue submission template? 

I'll close the issue then.
Thanks and best regards,

Katarzyna

**Comment by cjw85** [comment]
Hi @katsikora,

Our included profiles are deliberately minimal such that they should work in "basic" environments.

We don't wish to bloat our code bases with the plethora of config that might be required to run nextflow code in everyone's differently configured HPC setups. Nor do we believe it terribly wise to follow nf-core's approach of publishing these publicly.

We recommend supplying any configuration that is bespoke to your environment in a secondary [configuration file](https://www.nextflow.io/docs/latest/config.html).

**Comment by katsikora** [comment]
Hi @cjw85 ,

that's alright, I understand. 

Best wishes,

Katarzyna

**Comment by callumparr** [comment]
@katsikora If you do not mind, may you provide some code snippet of how you got it to run with slurm? 

If you have multiple samples, do you submit them all at once in an array job or split the jobs up, with one for each sample?

**Comment by katsikora** [comment]
Hi @callumparr,

I've added this to the nextflow config:

```
apptainer {
        apptainer {
            enabled = true
            autoMounts = true
            process.executor = 'slurm'
            process.beforeScript = 'module load singularity'
            process.cpus = 4
            process.memory = "40G" 
            process.time = "6h"
        }
    }
```

I've also added slurm to the list of executors:

```
$slurm  {
        cpus = 4
        memory = "8 GB"
        time = "6h"
    }
```

I've added cpus, memory and time specifications to the processes listed in the nextflow config. It lloks like the process-specific resource specifications override whatever is specified in the `slurm` executor or in the `apptainer` profile.

That's it on the config side.

Then, I module load all necessary software (singularity/apptainer, nextflow), and finally run the test command with -profile apptainer and providing the modified nextflow config.

Currently, I was only able to test processing of one sample at a time. This is not too bad, as you have implemented a scatter-gather process that speeds up digestion and alignment. But the genome index gets generated with every sample, which is a bit of a pity.
Submitting the main process as an array job (or not) to the slurm cluster is not an option for me - in our setting, worker nodes are not allowed to submit jobs. I have to run the main process on the head node, and let nextflow submit jobs to slurm.

I've seen that you have some implementation for nextflow `channels`, which I understand should allow for processing multiple samples at the same time. What would have the commandline look then? Multiple `--fastq` calls, or rather passing a folder to `--fastq`?

Thanks a bunch, and best wishes,

Katarzyna

**Comment by callumparr** [comment]
So far i have some test data where I have multiplexed several libraries and then created a concatenated fastq for each barcoded sample.

I've then created a config file in which array script can place in the input fastq and output directory for each sample. It downloads an image to each TMPDIR but then this is deleted when the job finishes. The guy who was processing pore-c data before he left was splitting the fastq as a job on our scheduler back it was a snakemake pipeline. Here as I want to process multiple samples at the same time I just concatenate them

I just wondered if there was something nextflow could handle itself if we provide a sample sheet of samples and barcodes and a directory to input fastq/ubam. 

Not sure I get the nuisance of nextflow and then with slurm on top of it is just confusing me. 

```
#!/bin/sh
#SBATCH --time=24:00:00
#SBATCH --cpus-per-task=4
#SBATCH --ntasks=1
#SBATCH --partition=batch
#SBATCH --job-name=array_pore-c
#SBATCH --output=/work/callum/apac-seq/slurm_logs/slurm_%x_%j.out
#SBATCH --error=/work/callum/apac-seq/slurm_logs/slurm_%x_%j.err
#SBATCH --array=1-8

# Read in config
config=/analysisdata/rawseq/fastq/SHARED/000079/APAC_seq_Fantom6_iPSC_20230710/sample_sheet.tsv

# Extract the sample name and file path for primer-chop files on guppy basecalls
sample=$(awk -v ArrayTaskID=$SLURM_ARRAY_TASK_ID '$1==ArrayTaskID {print $2}' $config)

hash=$(awk -v ArrayTaskID=$SLURM_ARRAY_TASK_ID '$1==ArrayTaskID {print $3}' $config)

barcode=$(awk -v ArrayTaskID=$SLURM_ARRAY_TASK_ID '$1==ArrayTaskID {print $4}' $config)

dir=$(awk -v ArrayTaskID=$SLURM_ARRAY_TASK_ID '$1==ArrayTaskID {print $5}' $config)

genome=/osc-fs_home/scratch/callum/Genome_files/GRCh38_no_alt_analysis_set_GCA_000001405.15.fasta
echo $TMPDIR

cd $TMPDIR

nextflow run epi2me-labs/wf-pore-c --fastq ${dir}/super_accuracy/pass/${barcode}/fastq_runid_${hash}_${barcode}_pass.fastq.gz --ref ${genome} --mcool_resolutions 1000,2000,3000 \
 --cutter DpnII --pairs --chromunity --paired_end --filter_pairs --paired_end_minimum_distance 100 --paired_end_maximum_distance 200 --chromunity --chromunity_merge_distance 5 \
--mcool -profile singularity --out_dir $TMPDIR/${barcode} --coverage

wait

mv $TMPDIR/${barcode} /work/callum/apac-seq/

wait

```

**Comment by sarahjeeeze** [comment]
Hi, the workflow should work with multiple samples. You can see more details in the help text in the sample_sheet and param and see an example in the test_data folder in the repo of how to provide per sample parameters in the param sheet

**Comment by callumparr** [comment]
> Hi, the workflow should work with multiple samples. You can see more details in the help text in the sample_sheet and param_sheet and see an example in the test_data folder in the repo of how to provide per sample parameters in the param sheet

Thank you @sarahjeeeze can i confirm something, should the param_sheet also list he vcf file for s02 sample? I got an error during the processing related to this sample and whatshap. 

Also when i use --sample_sheet and --param_sheet I still need to use --cutter flag for some reason. As we list the cutter listed in the param file why is it necessary to also call the cutter in the nextflow command?

**Comment by sarahjeeeze** [comment]
Hi Callum, looks like we need to improve the error handling and cutter requirement here. Re-opening this and will look in to this shortly.

**Comment by hgingras** [comment]
> Hi, thanks for responding. I've added an `apptainer` profile to the config that works with our slurm cluster. The `singularity` profile wasn't working out of the box.
> 
> I've solved the issue by passing setting the NXF_SINGULARITY_CACHEDIR variable in my .bash_profile to a path that the worker nodes can see. I guess the issue was cluster environment related. Would you like to add this as an option to the issue submission template?
> 
> I'll close the issue then. Thanks and best regards,
> 
> Katarzyna

Hi Katarzyna,

I am working in an environment very similar to you. I have the same error than you : fastcat command not found... 

I added what you suggested in the nextflow config file. Can you send me the full command you have set-up with NXF_SINGULARITY_CACHEDIR. Did you change the name for NXF_APPTAINER_CACHEDIR? I haven't been able to run anything yet. 

This is my command with the test data:

nextflow run main.nf -c nextflow.config  --fastq test_data/porec_test.concatemers.fastq  --ref test_data/porec_test.fasta  --phased_vcf test_data/porec_test.phased_variants.vcf.gz  --cutter NlaIII  --vcf test_data/porec_test.phased_variants.vcf.gz --pairs  --chromunity --paired_end --filter_pairs --paired_end_minimum_distance 100  --paired_end_maximum_distance 200  --out_dir outputPoreC-test  -profile apptainer --with-apptainer /home/helene/scratch/Ticket/wf-pore-C/wf-pore-C_apptainer/wf-pore-c/wf-pore-c_latest.sif

Thanks for your help,

Hélène

**Comment by hgingras** [comment]
I was able to figure out what I need to run my script! Thanks to all the comments.

**Comment by sarahjeeeze** [comment]
Hi, we have now removed the requirement for a seperate parmaeter sheet and per sample params can be added to the sample sheet, see the documentation for information. We have also removed cutter from the required parameters as mentioned above.

**Comment by sarahjeeeze** [comment]
Closing as this issue was resolved.
