### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by molecule53** [epi2me-labs/wf-pore-c#2]
### What happened?

I would like to analyze my Pore-C data. I would like to run the analysis on AWS using commands.

(base) ubuntu@ip-172-31-25-247:/Data1$ ./nextflow run epi2me-labs/wf-porec --ubam test_data/porec_test.concatemers.bam --ref test_data/porec_test.genome.fasta  --mcool_resolutions 10,20,30 
N E X T F L O W  ~  version 22.10.7
Pulling epi2me-labs/wf-porec ...
WARN: Cannot read project manifest -- Cause: Remote resource not found: https://api.github.com/repos/epi2me-labs/wf-porec/contents/nextflow.config
Remote resource not found: https://api.github.com/repos/epi2me-labs/wf-porec/contents/main.nf

### Operating System

ubuntu 20.04

### Workflow Execution

Command line

### Workflow Execution - CLI Execution Profile

None

### Workflow Version

N E X T F L O W  ~  version 22.10.7

### Relevant log output

```shell
(base) ubuntu@ip-172-31-25-247:/Data1$ ./nextflow run epi2me-labs/wf-porec --ubam test_data/porec_test.concatemers.bam --ref test_data/porec_test.genome.fasta  --mcool_resolutions 10,20,30 
N E X T F L O W  ~  version 22.10.7
Pulling epi2me-labs/wf-porec ...
WARN: Cannot read project manifest -- Cause: Remote resource not found: https://api.github.com/repos/epi2me-labs/wf-porec/contents/nextflow.config
Remote resource not found: https://api.github.com/repos/epi2me-labs/wf-porec/contents/main.nf
```

**Comment by molecule53** [comment]
I got another error:

(base) ***@***.***:/Data1/wf-pore-c$ ../nextflow run epi2me-labs/wf-pore-c --ubam test_data/porec_test.concatemers.bam --ref test_data/porec_test.fasta --cutter NlaIII --mcool_resolutions 10,20,30


N E X T F L O W  ~  version 22.10.7

Launching `https://github.com/epi2me-labs/wf-pore-c` [mad_torricelli] DSL2 - revision: 897260b7c1 [master]

WARN: A process with name 'merge_paired_end_bams' is defined more than once in module script: /home/ubuntu/.nextflow/assets/epi2me-labs/wf-pore-c/main.nf -- Make sure to not define the same function as process


WARN: Found unexpected parameters:

* --process_label: wfporec

* --sample_id: null

* --version: false

- Ignore this warning: params.schema_ignore_params = "process_label,sample_id,version"



||||||||||   _____ ____ ___ ____  __  __ _____      _       _

||||||||||  | ____|  _ \_ _|___ \|  \/  | ____|    | | __ _| |__  ___

|||||       |  _| | |_) | |  __) | |\/| |  _| _____| |/ _` | '_ \/ __|

|||||       | |___|  __/| | / __/| |  | | |__|_____| | (_| | |_) \__ \

||||||||||  |_____|_|  |___|_____|_|  |_|_____|    |_|\__,_|_.__/|___/

||||||||||  wf-porec v0.0.2-g897260b

--------------------------------------------------------------------------------

Core Nextflow options

  revision                   : master

  runName                    : mad_torricelli

  containerEngine            : docker

  launchDir                  : /Data1/wf-pore-c

  workDir                    : /Data1/wf-pore-c/work

  projectDir                 : /home/ubuntu/.nextflow/assets/epi2me-labs/wf-pore-c

  userName                   : ubuntu

  profile                    : standard

  configFiles                : /home/ubuntu/.nextflow/assets/epi2me-labs/wf-pore-c/nextflow.config, /Data1/wf-pore-c/nextflow.config


Input Options

  ubam                       : test_data/porec_test.concatemers.bam

  ref                        : test_data/porec_test.fasta


Advanced Options

  ubam_map_threads           : 2

  digest_annotate_threads    : 1

  ubam_bam2fq_threads        : 1


Chromunity Options

  chromunity_merge_distance  : null


4DN files Options

  mcool_resolutions          : 10,20,30


Paired-end BAM Options

  paired_end_minimum_distance: null

  paired_end_maximum_distance: null


Other parameters

  process_label              : wfporec

  sample_id                  : null


!! Only displaying parameters that differ from the pipeline defaults !!

--------------------------------------------------------------------------------

If you use epi2me-labs/wf-porec for your analysis please cite:


* The nf-core framework

  https://doi.org/10.1038/s41587-020-0439-x



--------------------------------------------------------------------------------

This is epi2me-labs/wf-porec v0.0.2-g897260b.

--------------------------------------------------------------------------------

WARN: Access to undefined parameter `sample_sheet` -- Initialise it to a default value eg. `params.sample_sheet = some_value`

executor >  local (1)

[ad/c2fc03] process > POREC:prepare_genome:index_ref_mmi (1) [100%] 1 of 1, failed: 1 ✘

[-        ] process > POREC:digest_align_annotate            -

[-        ] process > POREC:haplotag_alignments              -

[-        ] process > POREC:merge_coordsorted_bams           -

[-        ] process > POREC:merge_namesorted_bams            -

Error executing process > 'POREC:prepare_genome:index_ref_mmi (1)'


Caused by:

  Process `POREC:prepare_genome:index_ref_mmi (1)` terminated with an error exit status (127)


Command executed:


  minimap2 -x map-ont -d "reference.fasta.mmi" "reference.fasta"


Command exit status:

  127


Command output:

  (empty)


Command error:

  .command.run: line 281: docker: command not found


Work dir:

  /Data1/wf-pore-c/work/ad/c2fc0347531c93033d98b818dd611f


Tip: you can replicate the issue by changing to the process work dir and entering the command `bash .command.run`

________________________________
From: Sam Nicholls ***@***.***>
Sent: Thursday, March 23, 2023 1:29 PM
To: epi2me-labs/wf-pore-c ***@***.***>
Cc: McKinlay, Anastasia ***@***.***>; Mention ***@***.***>
Subject: [External] Re: [epi2me-labs/wf-pore-c] [Bug]: (Issue #2)

This message was sent from a non-IU address. Please exercise caution when clicking links or opening attachments from external sources.


@molecule53<https://github.com/molecule53> It looks like you have a typo in the workflow name, please try nextflow run epi2me-labs/wf-pore-c.

**Comment by molecule53** [comment]
Just in case if this is important:
(base) ubuntu@ip-172-31-25-247:/Data1/wf-pore-c/work/ad/c2fc0347531c93033d98b818dd611f$ ls
reference.fasta

**Comment by SamStudio8** [comment]
Hi @molecule53, the pertinent part of your log is here:
```
Command error:

  .command.run: line 281: docker: command not found
```
You need to install Docker into your environment to allow the workflow to run.

**Comment by molecule53** [comment]
I don't run this from my Desktop. Should I install Docker on EC2 with Ubuntu (AWS)? Would you be able to guide me to the version of Docker?

Thank you!

**Comment by cjw85** [comment]
Hi @molecule53,

Aiding you to install docker is perhaps beyond the scope of our ability to support you through this channel. There are plenty of guides on the internet detailing how to install and setup docker for Ubuntu.

**Comment by SamStudio8** [comment]
Hi @molecule53, our workflows use [Docker](https://www.docker.com/products/docker-desktop/) to simplify the distribution and running of bioinformatics software needed by the workflow. You need to install Docker into your environment to allow the workflow to run.

As @cjw85 has indicated, installing Docker is beyond the scope of our ability to support you through this channel but for local execution (eg. your laptop or desktop) we would recommend trying our [EPI2ME Labs application](https://labs.epi2me.io/installation/), when first run EPI2ME Labs will guide you through installing Docker. If you want to run our workflows on your institution’s cluster, you should speak to your system administrator about “how to run Docker or Singularity images”.
