### ISSUE TITLE
INFO:    underlay of /etc/localtime required more than 50 (78) bind mounts

### ISSUE THREAD

**Issue by hgingras** [epi2me-labs/wf-pore-c#20]
### What happened?

I was able to run the pipeline with test_data using apptainer with this command line:

nextflow run main.nf -c nextflow.config \
 --fastq test_data/porec_test.concatemers.fastq \
 --ref test_data/porec_test.fasta \
 --phased_vcf test_data/porec_test.phased_variants.vcf.gz \
 --cutter NlaIII \
 --vcf test_data/porec_test.phased_variants.vcf.gz --pairs \
 --chromunity --paired_end --filter_pairs --paired_end_minimum_distance 100 \
 --paired_end_maximum_distance 200 \
 --out_dir outputPoreC-test-25-1 \
 -profile apptainer

When trying with local data with same nextflow.config:

nextflow run main.nf -c nextflow.config \
 --fastq /home/oksanak/scratch/N144/N141N144.fastq \
 --ref /home/oksanak/scratch/N144/Tb.fasta \
 --cutter HindIII \
 --mcool_resolutions 1000,2000,3000 \
 --pairs  --chromunity --mcool \
 --out_dir /home/oksanak/scratch/N141N144BF_results \
 -profile apptainer

I got this error:

ERROR ~ Error executing process > 'POREC:fastcat (1)'

Caused by:
  Process `POREC:fastcat (1)` terminated with an error exit status (140)

Command executed:

  mkdir fastcat_stats
  fastcat             -s N141N144             -r fastcat_stats/per-read-stats.tsv             -f fastcat_stats/per-file-stats.tsv                          N141N144.fastq             | bgzip -@ 4 > seqs.fastq.gz

Command exit status:
  140

Command output:
  (empty)

Command error:
  INFO:    underlay of /etc/localtime required more than 50 (78) bind mounts

Do you have any idea what could cause this error?

Best regards,

Hélène

### Operating System

ubuntu 18.04

### Workflow Execution

Command line

### Workflow Execution - CLI Execution Profile

Singularity

### Workflow Version

0.0.8

### Relevant log output

```shell
[bb/297406] process > POREC:fastcat (1)              [100%] 1 of 1, failed: 1 ✘
[-        ] process > POREC:index_ubam               -
[c1/4ecb5c] process > POREC:prepare_genome:index_... [100%] 1 of 1 ✔
[d8/0354a0] process > POREC:prepare_genome:index_... [100%] 1 of 1 ✔
[-        ] process > POREC:digest_align_annotate    -
[-        ] process > POREC:haplotag_alignments      -
[-        ] process > POREC:merge_coordsorted_bams   -
[-        ] process > POREC:merge_namesorted_bams    -
[-        ] process > POREC:create_restriction_bed   -
[-        ] process > POREC:to_pairs_file            -
[-        ] process > POREC:pairsToCooler            -
[-        ] process > POREC:merge_mcools             -
[-        ] process > POREC:merge_pairs              -
[-        ] process > POREC:merge_pairs_stats        -
[-        ] process > POREC:pair_stats_report        -
[-        ] process > POREC:merge_parquets_to_dat... -
[b8/ac7b3e] process > POREC:getVersions              [100%] 1 of 1 ✔
[01/badb21] process > POREC:getParams                [100%] 1 of 1 ✔
[-        ] process > POREC:makeReport               -
ERROR ~ Error executing process > 'POREC:fastcat (1)'

Caused by:
  Process `POREC:fastcat (1)` terminated with an error exit status (140)

Command executed:

  mkdir fastcat_stats
  fastcat             -s N141N144             -r fastcat_stats/per-read-stats.tsv             -f fastcat_stats/per-file-stats.tsv                          N141N144.fastq             | bgzip -@ 4 > seqs.fastq.gz

Command exit status:
  140

Command output:
  (empty)

Command error:
  INFO:    underlay of /etc/localtime required more than 50 (78) bind mounts

Work dir:
  /lustre04/scratch/oksanak/wf-pore-c-0.0.8/wf-pore-c/work/bb/297406210bef0b14c86c649524387c

Tip: when you have fixed the problem you can continue the execution adding the option `-resume` to the run command line

 -- Check '.nextflow.log' file for details
```

**Comment by sarahjeeeze** [comment]
Hi, exit 140 is usually an issue with your environment so in this case your singularity set up. Probably worth checking if you can run singilarity independently of the workflow using eg. 
```
singularity pull hello-world.sif shub://vsoch/hello-world 
singularity run hello-world.sif
```

And if someone else manages your cluster/environment then get in touch with them. You could also try docker if that is an option.

**Comment by hgingras** [comment]
Dear Sarahjeeeze,

I was a time issue. I was able to complete the analysis. You can close the issue. Thanks for your help.

**Comment by sarahjeeeze** [comment]
Thanks, closing.

**Comment by ywang285** [comment]
> ngularity set up. Probably worth checking if you can run singilarity independently of the workflow using eg.

Hi @hgingras, I encountered the same issue when running on our HPC using singularity. Could you please let me know how you solved this issue? Thanks!

**Comment by AlcaArctica** [comment]
Same issue here, how have you figured out how to solve it @ywang285 and @hgingras ?

**Comment by hgingras** [comment]
Hi @AlcaArctica , I have put together a document for the installation of Nanopore EPI2me workflows on the Alliance Clusters in Canada. Hoping this can help you. Last time modified was August 2024...

[Nanopore-EPI2me-Hélène_Gingras.pdf](https://github.com/user-attachments/files/28466103/Nanopore-EPI2me-Helene_Gingras.pdf)
