### ISSUE TITLE
[Question:] Does Pore-C pipeline support data from MNase/DNase-digested genome?

### ISSUE THREAD

**Issue by divinomas** [epi2me-labs/wf-pore-c#21]
### What happened?

Many Hi-C pipelines have provided support for the interaction data from MNase/DNase-digested genome.
Could we use Pore-C for a similar task? 
If so, simply set --cutter to null or ?
Thank you in advance.

### Operating System

Windows 10

### Workflow Execution

EPI2ME Labs desktop application

### Workflow Execution - CLI Execution Profile

None

### Workflow Version

0.0.8

### Relevant log output

```shell
?
```

**Comment by sarahjeeeze** [comment]
Hi, thanks for the feedback we will look in to this in the future.

**Comment by sarahjeeeze** [comment]
Closing as we won't be adding in the near future, but thanks for the feedback we may add it at some point.
