### ISSUE TITLE
[Bug]: Why is paired end maximum distance set to 200

### ISSUE THREAD

**Issue by markme123** [epi2me-labs/wf-pore-c#23]
### What happened?

Why is paired end maximum distance set to 200！which filters out a lot of contact,

### Operating System

ubuntu 20.04

### Workflow Execution

Command line

### Workflow Execution - CLI Execution Profile

None

### Workflow Version

0.08

### Relevant log output

```shell
no
```

**Comment by sarahjeeeze** [comment]
Hi, thanks for pointing this out. It's only in the example cmd/demo data the default paired end min and max aren't set but we will consider updating the example cmd.

**Comment by sarahjeeeze** [comment]
Closing as this is no longer set in the example command.
