### ISSUE TITLE
pairsToCooler

### ISSUE THREAD

**Issue by Oksanak22** [epi2me-labs/wf-pore-c#24]
### Ask away!

Hello!
I run the last version wf-pore-c-0.0.8 with a .fastq file on 30Gb. And it failed several times.
To be able to finish this analysis I made modifications by specifying  "ignore" for all the failed analyses for the "pairsToCooler" steps and it moved to the other tests.

Could you, please, do this modification (specify  "ignore" for all the failed analyses for the "pairsToCooler" steps) in the pipeline?

**Comment by SamStudio8** [comment]
Hi @Oksanak22, I am sorry to hear you are having trouble with the wf-pore-c workflow. Could you please open a new issue following the Bug report template so we can better understand the problems you are encountering on the pairsToCooler steps?
