### ISSUE TITLE
Resulting BAM file not working with SALSA?

### ISSUE THREAD

**Issue by sanalbert** [epi2me-labs/wf-pore-c#27]
### Ask away!

Hi, thanks for the great workflow! I have a question about the BAM file generated from wf-pore-c. I am not sure if this is a bug, because everything runs without any errors, but I am just concerned about the results.

I am trying to use Pore-C data to improve a HiFi assembly draft genome (made from Hifiasm), and used wf-pore-c to map my Pore-C reads to the reference.

```
./nextflow run epi2me-labs/wf-pore-c -profile singularity --fastq sample_porec.fq.gz --ref sample.asm.bp.p_ctg.fa --cutter NlaIII --chromunity --pairs --mcool --paired_end
```

From the `--pairs` results mapping seems to have gone fine, and I can see a lot of contact pair information. But when I take the resulting BAM file, convert to bedfile, and use for assembly in SALSA, no links are loaded, and the scaffolding does not improve.

This is the message from salsa:
```
bedfile loaded
Starting Iteration 1
bedfile started
bedfile loaded
Loading Hi-C links 
Hybrid scaffold graph loaded, nodes = 0 edges = 0
Hi-C implied edges = 0
```
I am not sure if `Hybrid scaffold graph loaded, nodes = 0 edges = 0` is normal. From this I am assumming that salsa is not recognizing the contact information generated in wf-pore-c. Has anyone seen this type of behavior, and if this is truely problematic, would there be a way to fix it?

I have the same results using the [test_data](https://github.com/epi2me-labs/wf-pore-c/tree/master/test_data) from this repository.  This is the [null.pairs.stats.html](https://github.com/epi2me-labs/wf-pore-c/files/12471140/null.pairs.stats.html.txt) file; may there be something I am missing?

I have reported the [same issue at salsa](https://github.com/marbl/SALSA/issues/175#issue-1869292788) but I have no idea where the problem is from, salsa or wf-pore-c, so I am also posting it here.

I would greatly appreciate any comments or ideas regarding this issue. Thank you for all your support.

**Comment by sarahjeeeze** [comment]
Hi, thanks for letting us know. We will investigate this and get back to you.

**Comment by sanalbert** [comment]
> Would you be able to share the cmd/cmds you are using for salsa?

Hi, thanks for your support.
I am following the commands as documented in [salsa](https://github.com/marbl/SALSA):
```
bamToBed -i null.ns.bam > alignment.bed
sort -k 4 alignment.bed > tmp && mv tmp alignment.bed
# Although the bam/bed files should already be sorted by name I used sort just in case

samtools faidx sample.asm.bp.p_ctg.fa > contigs.fa.fai

python SALSA/run_pipeline.py -a sample.asm.bp.p_ctg.fa -l contigs.fa.fai -b alignment.bed -e CATG -o scaffolds
```

**Comment by sarahjeeeze** [comment]
thanks

**Comment by sanalbert** [comment]
I have tried scaffolding with [yahs](https://github.com/c-zhou/yahs) as well, with the same results; apparently my bedfile does not contain any information on inter-links. Would there be a way to diagnose whether if my bed/bam file, or even the original pore-c data, actually contains properly linked reads?

Sorry for the such naïve questions, I have much to learn, and I would really appreciate any of your advice.

**Comment by sarahjeeeze** [comment]
Hi, we don't currently support either of these downstream tools but are looking in to it and will get back to you soon. Thanks for raising this issue.

**Comment by sarahjeeeze** [comment]
We will hopefully look in to adding support for this or another scaffolding tool in the future but in the short term we do not support the downstream salsa scaffolding tool so am closing this for now. Thanks again for the feedback.
