### ISSUE TITLE
How the data is filtered in Pore-C

### ISSUE THREAD

**Issue by Oksanak22** [epi2me-labs/wf-pore-c#29]
### Ask away!

How the data is filtered in Pore-C pipeline and what is a mapping quality score?

**Comment by sarahjeeeze** [comment]
Hi, thanks for the question! What do you mean by filtering? We don't filter out any data based on read length or quality we digest and align all the reads to reference and use the alignments to create the pairs file etc. There are some optional filtering parameters if you have selected the paired end bam which are paired_end_minimum/maximum_distance to remove trans pairs and cis- pairs separated by a distance shorter/greater than this value see the --help parameter text for further explanation on those. The mapping quality comes from the minimap2 alignment and is a phred-scaled probability of the alignment being wrong. Let me know if any further explanation is required.

**Comment by Oksanak22** [comment]
Thank you, i understood about filtering. What about the parameters that you are using for Pore-c tools?

**Comment by Oksanak22** [comment]
@sarahjeeeze could you, please, point out where is the phred-scaled probability parameter in a script? And what is the value?

**Comment by sarahjeeeze** [comment]
When you say Pore-C tools do you mean the python package? This uses the workflow parameters `--chromunity` which is a boolean and `--chromunity_merge_distance` (merge colinear alignments separated by less than this base pair distance into a single monomer) and the `--paired_end` parameters mentioned in my last comment. The map quality score is given in the output .pair format file in the `mapq` column and is added by the minimap2 tool which gives a definition `Mapping quality (0-255 with 255 for missing)` you can read more about the phred scale [here](https://en.wikipedia.org/wiki/Phred_quality_score)

**Comment by sarahjeeeze** [comment]
Closing through lack of response.
