### ISSUE TITLE
How to make the workflow output work with the "chromunity" R package?

### ISSUE THREAD

**Issue by katsikora** [epi2me-labs/wf-pore-c#30]
### Ask away!

Dear Developers,

I'd like to clarify the following:
the parquet files in the chromunity output folder have the following column names: "cid", "chrom", "start", "end", "num_fragments",
 while the "Chromunity" R package looks for the following columns: "read_name" , "chrom", "start", "end", "pass_filter".
Applying the `parquet2gr function on those parquet files throws an error related to unmatching suffix. 

1. Are the parquet files in the chromunity folder output by the workflow the correct input to the `parquet2gr` function of the "Chromunity" R package?
If so, then what would be the correct way to call the function?
2. If these are not the correct input files, then which files output by the workflow should be used instead?

My question might be somewhat related to #13 , but the answer wasn't clear to me.

Let me know if you have questions or comments,

Best wishes,

Katarzyna

**Comment by sadhanagaddam3** [comment]
I'm having the same issue. Instead of using the parquet2gr function, I have used the below code.

all.paths = data.table(file_path = dir("directory", all.files = TRUE, 
                                       recursive = TRUE, full = TRUE))[grepl("*pore_c.parquet*", 
                                                                             file_path)]
col_names = c("cid", "chrom", "start", "end", "num_fragments")
parq.list = pbmclapply(1:nrow(all.paths), function(k) {
  parq.al = read_parquet(all.paths[k]$file_path, col_select = col_names)
  parq.al = as.data.table(parq.al)
  return(parq.al)
}, mc.cores = 2)
parq.dt = rbindlist(parq.list, fill = TRUE)
parq.gr = dt2gr(parq.dt)

It worked fine, but I feel there will be an issue in downstream analysis by using this approach. Can you please let me know if my approach is okay to use or suggest to me the best way to run the "Chromunity" package?

Best,
Sadhana

**Comment by sarahjeeeze** [comment]
Hi, thanks for pointing this out. We will investigate this and update the parquet file headers. Thanks @sadhanagaddam3 for sharing your current work around!

**Comment by sadhanagaddam3** [comment]
Want to follow up on the issue. Can you please let me know if you are able to fix it and how to generate new parquet files to run Chromunity?

**Comment by sarahjeeeze** [comment]
This should now be available in the prerelease and we will include it in the next release.

**Comment by katsikora** [comment]
Great, thanks a bunch!

**Comment by sadhanagaddam3** [comment]
Thank you, Sarah! The latest release version I can see is updated in September. May I know how to clone the prerelease version?

**Comment by sarahjeeeze** [comment]
Hey, so run the workflow cmd as usual and add revision parameter so eg. `nextflow run... -r prerelease`

**Comment by sarahjeeeze** [comment]
Hi, did you have any luck with this?

**Comment by katsikora** [comment]
Hi,

for me running the `nextflow run .. -r prerelease` itself worked, but I still got an issue with chromunity:
I fed the parquet files from the folder `null.chromunity.parquet`, after renaming them to match the required suffix `.pore_c.parquet`.

The function `parquet2gr` failed for me. Column names required by this function are `col_names = c("read_name", "chrom", "start", "end", "pass_filter")`, while the column names I found in one of the parquet chunks are: `cid, chrom, start, end, num_fragments`.

```
> parq.al = read_parquet(file.path(indir,"part00694.pore_c.parquet"))
> str(parq.al)
tibble [186,485 × 5] (S3: tbl_df/tbl/data.frame)
 $ cid          : chr [1:186485] "42e6c3de-5470-4933-912e-761a6d3213dd" "42e6c3de-5470-4933-912e-761a6d3213dd" "42e6c3de-5470-4933-912e-761a6d3213dd" "42e6c3de-5470-4933-912e-761a6d3213dd" ...
 $ chrom        : chr [1:186485] "4" "4" "16" "16" ...
 $ start        : int [1:186485] 102552394 102552158 46205134 46211364 46211177 46210415 71603240 38482798 59810990 60341555 ...
 $ end          : int [1:186485] 102552498 102552379 46205295 46211794 46211285 46211151 71603696 38482974 59811492 60342171 ...
 $ num_fragments: int [1:186485] 1 1 1 1 1 1 1 1 2 3 ...
```

Best,

Katarzyna

**Comment by sarahjeeeze** [comment]
thanks for letting us know, I guess for now you can rename them but we will update the workflow to fix the column names

**Comment by sarahjeeeze** [comment]
Hi, did you definitely pull the latest version the columns should now be eg.
```
+-----------+-------------+---------+---------+-------+-----------------+---------------+
| cid       | read_name   | chrom   |   start |   end |   num_fragments | pass_filter   |
|-----------+-------------+---------+---------+-------+-----------------+---------------|
| CONCAT200 | CONCAT200   | chr2    |       0 |   537 |               1 | TRUE          |
```

**Comment by sarahjeeeze** [comment]
Perhaps try `nextflow pull epi2me-labs/wf-pore-c` and try again to ensure the container is up to date. Just tried to latest version and get in R 
```
> parq <- read_parquet("part00002.parquet")
> head(parq)
      cid read_name chrom start  end num_fragments pass_filter
1 CONCAT0   CONCAT0  chr2  5442 5512             1        TRUE
2 CONCAT0   CONCAT0  chr1   601 3003             2        TRUE
3 CONCAT0   CONCAT0  chr2  5529 6455             1        TRUE
4 CONCAT0   CONCAT0  chr2  6455 6538             1        TRUE
5 CONCAT0   CONCAT0  chr2   537 5442             1        TRUE
```

**Comment by katsikora** [comment]
Hi Sarahjeeze,

I've tried with `nextflow pull epi2me-labs/wf-pore-c`, and then `nextflow run epi2me-labs/wf-pore-c ... -r prerelease` and I still get the 'old' columns.
How do you run your nextflow command?

Thank you for your help,
Best wishes,

Katarzyna

**Comment by sarahjeeeze** [comment]
Thanks for letting me know, in the next release the container should be upated

**Comment by sarahjeeeze** [comment]
Hi again, could you try the latest version? I think it should work now. Sorry I think we had not updated the container correctly before.

**Comment by katsikora** [comment]
Hi,

yes, the parquet files in the chromunity folder can now be imported with the `chromunity::parquet2gr` function , after renaming the suffix to `pore_c.parquet`.

Best wishes,

Katarzyna
