### ISSUE TITLE
Question on interpreting output bam file

### ISSUE THREAD

**Issue by sanalbert** [epi2me-labs/wf-pore-c#31]
### Ask away!

Hello, can I ask one more question on the resulting bam file?

I am curious about the mapped read names; for example in my paired-end bam file which looks like this:

(using `samtools view -F0xD00 output/paired_end/null.ns.bam | cut -f1-9 | head`)
```
31964678-c1e4-4cd9-aa03-eedab558a0e7:0000:0318  89      ptg000004l      2680996 60      73M9D36M2D51M1I41M2I2M1D3M1D84M25S      *       0       0
31964678-c1e4-4cd9-aa03-eedab558a0e7:0318:0387  133     *       0       0       *       ptg000004l      2680996 0
31964678-c1e4-4cd9-aa03-eedab558a0e7:0000:0318  81      ptg000004l      2680996 60      73M9D36M2D51M1I41M2I2M1D3M1D84M25S      ptg000007l      5294886 2614046
31964678-c1e4-4cd9-aa03-eedab558a0e7:0387:0549  129     ptg000007l      5294886 60      111M2I45M4S     ptg000004l      2680996 -2614046
31964678-c1e4-4cd9-aa03-eedab558a0e7:0000:0318  81      ptg000004l      2680996 60      73M9D36M2D51M1I41M2I2M1D3M1D84M25S      ptg000080l      1500855 1180444
31964678-c1e4-4cd9-aa03-eedab558a0e7:0549:1013  145     ptg000080l      1500855 60      206M1I189M3D68M ptg000004l      2680996 -1180444
31964678-c1e4-4cd9-aa03-eedab558a0e7:0000:0318  81      ptg000004l      2680996 60      73M9D36M2D51M1I41M2I2M1D3M1D84M25S      ptg000006l      18804336        16123415
31964678-c1e4-4cd9-aa03-eedab558a0e7:1013:1098  129     ptg000006l      18804336        32      75M10S  ptg000004l      2680996 -16123415
31964678-c1e4-4cd9-aa03-eedab558a0e7:0318:0387  69      *       0       0       *       ptg000007l      5294886 0
31964678-c1e4-4cd9-aa03-eedab558a0e7:0387:0549  137     ptg000007l      5294886 60      111M2I45M4S     *       0       0
```

Each unique read name (1st column) is apparently mapped to only one position in a contig, but considering the mechanism of Pore-C this seems unrealistic. Does the pair of numbers after ":" mean something?
Then we have multiple records of the same read mapped to the same contig, same position (e.g. lines 3, 5, and 7). Is this normal behavior for Pore-C?

Please correct me if I have misunderstood the workflow. This is my first time handling pore-c data and I would really appreciate any help. Thank you for all your support!

**Comment by sanalbert** [comment]
Thank you for the explanation, I think I understand much better now.

Just to be sure, so from this data, different parts of the read `31964678-c1e4-4cd9-aa03-eedab558a0e7` were mapped to contigs `ptg000004l`, `ptg000007l`, `ptg000080l`, and `ptg000006l`, from which we can assume these contigs are in close proximity of each other?

**Comment by sanalbert** [comment]
Also can I ask how this "mock paired-end" bam is generated, differently from the default bam file?

Thank you!

**Comment by sarahjeeeze** [comment]
Hi, yes correct - different parts of the read were mapped to those contigs. For the second question the mock paired-end bam is generated using a script in the pore-c-py package https://github.com/epi2me-labs/pore-c-py, if of interest look at the align_tools.py script for the paired end parts - let me know if you would like further explanation.

The paired end bam differs in that for every combination of monomers from each chimeric read a paired end read will be output, so a left and right read for each vs the normal bam file which you will notice is much smaller as it only contains each monomer once. Hope this makes sense, let me know if not.

**Comment by sanalbert** [comment]
Thank you so much for all the explanations! I'm still working on downstream processes, but now I understand much more on handling pore-c data. Thanks for the help!

**Comment by sarahjeeeze** [comment]
Thanks, closing this for now.
