### ISSUE TITLE
HiC file from Wf-pore-C

### ISSUE THREAD

**Issue by Oksanak22** [epi2me-labs/wf-pore-c#32]
### Ask away!

Hello. 
If I set mcool_resolutions = '20000,40000,50000,100000N in .nextflow.config 
and --mcool_resolutions 10000,20000  in .sh file (bash file to run a wf-pore-c
module load apptainer/1.1.8 java/17.0.2 nextflow/23.04.3
nextflow run main.nf -c nextflow.config \
 --fastq /home/4.fastq \
  --ref /home/A_fork.fasta
 --mcool_resolutions 10000,20000 \
 --pairs --chromunity --mcool
--out_dir 20k_A \
 --hi_c \
 -profile apptainer) 
what will be the resolution of my .hic file 10000 or 20000? 
And what is the input to create a .hic file? .mcool or .pairs file?

Thank you.

**Comment by sarahjeeeze** [comment]
Hi, the workflow will use any cmd line arguments you set so the `--mcool_resolutions 10000,20000` as priority so will override anything in the nextflow.config file. The cooler tool outputs multiple resolutions so it should have resolutions of 10000 and 20000. 

The final question Im not sure what you mean by input.. parameters for the workflow or input we use to create those files? If the first then its just as you have it (hi_c, mcool, pairs) and if the second then the pairs file is created from the name sorted bam file, the mcool file is created using the pairs file and the hi_c file is created using the pairs file.

**Comment by Oksanak22** [comment]
Thank you for the explanation.

**Comment by sarahjeeeze** [comment]
Feel free to close this is the explanation is sufficient.
