### ISSUE TITLE
What scaffolder to use with .hic file?

### ISSUE THREAD

**Issue by SwenDiepstraten** [epi2me-labs/wf-pore-c#36]
### Ask away!

Hello, thank you for developing this pipeline.

I was able to create a .hic file, but I want to use this to improve my genome assembly. I want to scaffold my assembly based on the contacts to hopefully create a chromosome level assembly. Do you have any recommendations of scaffolders that work well with the output from this tool?

Thanks in advance!

**Comment by sarahjeeeze** [comment]
Hi. It should work with the Salsa2 tool but this is not something we have official support for at the moment and we have not tested it that much. We may look at adding support for a scaffolding tool it in the future - probably sometime next year. Would be interested to hear if you find any tools that work well.

**Comment by SwenDiepstraten** [comment]
Salsa2 says that there are no nodes and edges in the hi-c file:

Hybrid scaffold graph loaded, nodes = 0 edges = 0
Hi-C implied edges = 0

Is this a known problem? is there a known solution to this?

**Comment by sarahjeeeze** [comment]
Hi, sorry that does not look right. We will investigate this at some point, and try to find a scaffolding tool that works or work out if we need to edit our outputs someway so they work with the scaffolders.

**Comment by sarahjeeeze** [comment]
Hi,  Thanks for raising this. You could use the Snakemake pipeline which has support for salsa 2 but this is unmaintained. I believe the outputs of this workflow do work with scaffolder Yahs but it may require an extra step, we are looking in to adding support for a scaffolder in the near future.

**Comment by sarahjeeeze** [comment]
Closing through lack of response, as mentioned we are looking to add some support for a scaffolder in the future.
