### ISSUE TITLE
CZI EOSS6

### ISSUE THREAD

**Issue by nvictus** [epi2me-labs/wf-pore-c#38]
### Ask away!

Hello Pore-C developers!

I'm the original author of cooler, PI at UMass Medical School, and one of the leads at [Open2C](https://github.com/open2c).

My lab recently got approval to submit a full proposal for the CZI [EOSS](https://chanzuckerberg.com/rfa/essential-open-source-software-for-science/) Cycle 6 program, where we are proposing enhancements to the cooler library to improve accessibility and interoperability of 3D genomics data. 

As you use Open2C software in your multi-contact workflows, we were wondering if there might be any interest in providing a letter of support on behalf of yourselves or The Nanopore Community.

Thank you for your awesome research and open-source work!

-Nezar

**Comment by cjw85** [comment]
Hi @nvictus,

I've forwarded this request to the scientific team that developed the original implementation of this workflow.

**Comment by eharr** [comment]
Hi @nvictus,

I just emailed you at the address listed in your profile.
