### ISSUE TITLE
samtools index

### ISSUE THREAD

**Issue by hgingras** [epi2me-labs/wf-pore-c#4]
### What happened?

When working with version 0.0.2, no problems running this command with test data.

nextflow run main.nf -c nextflow.config --ubam test_data/porec_test.concatemers.fastq --ref test_data/porec_test.fasta --cutter NlaIII -profile local --out_dir outputPoreC

With version 0.0.3, I am getting this error message : 
__________________________________________________________
Command executed:

  source /home/icestari/projects/def-icestari/icestari/Pore-C/wf-pore-c/Pore_C.sh
  mkdir bamstats
  if [ -d porec_test.concatemers.fastq ]; then
      samtools index -M porec_test.concatemers.fastq/*.*bam
      bamstats  -s porec_test porec_test.concatemers.fastq/*.*bam | head -n +1 > bamstats/per-read-stats.tsv
      for file in porec_test.concatemers.fastq/*.*bam; do
          bamstats  -s porec_test  --unmapped $file | tail -n +2 >> bamstats/per-read-stats.tsv
          cat $file >> output.bam
      done
      mv porec_test.concatemers.fastq bams;
  else
      samtools index -M porec_test.concatemers.fastq
      bamstats  -s porec_test  --unmapped porec_test.concatemers.fastq > bamstats/per-read-stats.tsv
      mv porec_test.concatemers.fastq output.bam
  fi

Command exit status:
  1

Command output:
  (empty)

Command error:

  samtools index: "porec_test.concatemers.fastq" is in a format that cannot be usefully indexed
_____________________________________________________________
Do you have any ideas why this is happening now?

Thanks,

Hélène

### Operating System

ubuntu 18.04

### Workflow Execution

Other (please describe)

### Workflow Execution - CLI Execution Profile

None

### Workflow Version

0.0.3

### Relevant log output

```shell
__________________________________________________________
Command executed:

  source /home/icestari/projects/def-icestari/icestari/Pore-C/wf-pore-c/Pore_C.sh
  mkdir bamstats
  if [ -d porec_test.concatemers.fastq ]; then
      samtools index -M porec_test.concatemers.fastq/*.*bam
      bamstats  -s porec_test porec_test.concatemers.fastq/*.*bam | head -n +1 > bamstats/per-read-stats.tsv
      for file in porec_test.concatemers.fastq/*.*bam; do
          bamstats  -s porec_test  --unmapped $file | tail -n +2 >> bamstats/per-read-stats.tsv
          cat $file >> output.bam
      done
      mv porec_test.concatemers.fastq bams;
  else
      samtools index -M porec_test.concatemers.fastq
      bamstats  -s porec_test  --unmapped porec_test.concatemers.fastq > bamstats/per-read-stats.tsv
      mv porec_test.concatemers.fastq output.bam
  fi

Command exit status:
  1

Command output:
  (empty)

Command error:

  samtools index: "porec_test.concatemers.fastq" is in a format that cannot be usefully indexed
_____________________________________________________________
```

**Comment by sarahjeeeze** [comment]
Hi, in v0.0.3 the input type must be specified with either `--fastq` or `--ubam`. You have `--ubam` followed by a fastq file, try changing that to `--fastq`.
