### ISSUE TITLE
why .hic file in juice box have lots of black line 

### ISSUE THREAD

**Issue by markme123** [epi2me-labs/wf-pore-c#40]
### Ask away!

![企业微信截图_20231203024530](https://github.com/epi2me-labs/wf-pore-c/assets/49668290/a449d80a-39c1-4cb4-bc88-fd46c72f1997)

**Comment by sarahjeeeze** [comment]
Hi, thanks for the feedback. What reference are you using? And are you using the juicebox web app? https://aidenlab.org/juicebox/. I do not get these black lines with a human data set using GRCh38 reference genome

**Comment by sarahjeeeze** [comment]
Hi, it sounds more like a question for the juicebox team.

**Comment by sarahjeeeze** [comment]
Closing as not relevant to the pore-c workflow but the juicer tool
