### ISSUE TITLE
.command.sh: line 2:    33 Killed   minimap2 -x map-ont -d "reference.fasta.mmi" "reference.fasta"

### ISSUE THREAD

**Issue by socialhang** [epi2me-labs/wf-pore-c#41]
hello @amblina @SamStudio8 @cjw85 @nrhorner 

I have some problems when I running

`curl: (6) Could not resolve host: www.nextflow.io
N E X T F L O W  ~  version 23.10.0
Launching `https://github.com/epi2me-labs/wf-pore-c` [berserk_rubens] DSL2 - revision: 265a1a4f88 [master]

||||||||||   _____ ____ ___ ____  __  __ _____      _       _
||||||||||  | ____|  _ \_ _|___ \|  \/  | ____|    | | __ _| |__  ___
|||||       |  _| | |_) | |  __) | |\/| |  _| _____| |/ _` | '_ \/ __|
|||||       | |___|  __/| | / __/| |  | | |__|_____| | (_| | |_) \__ \
||||||||||  |_____|_|  |___|_____|_|  |_|_____|    |_|\__,_|_.__/|___/
||||||||||  wf-pore-c v1.0.0-g265a1a4
--------------------------------------------------------------------------------
Core Nextflow options
  revision                   : master
  runName                    : berserk_rubens
  containerEngine            : docker
  container                  : [withLabel:wfporec:ontresearch/wf-pore-c:latest, withLabel:wf_common:ontresearch/wf-common:sha91452ece4f647f62b32dac3a614635a6f0d7f8b5]
  launchDir                  : /public/home/wangwen_lab/zonghang/project/new_muxu_project/20.T2T/03.assembly_test/14.porec/02.hifiasm_hifi_ul_hic_utg/ul10.fq.gz.tmp
  workDir                    : /public/home/wangwen_lab/zonghang/project/new_muxu_project/20.T2T/03.assembly_test/14.porec/02.hifiasm_hifi_ul_hic_utg/ul10.fq.gz.tmp/work
  projectDir                 : /public/home/wangwen_lab/zonghang/.nextflow/assets/epi2me-labs/wf-pore-c
  userName                   : zonghang
  profile                    : standard
  configFiles                : /public/home/wangwen_lab/zonghang/.nextflow/assets/epi2me-labs/wf-pore-c/nextflow.config

Input Options
  fastq                      : ../ul10.fq.gz
  ref                        : /public/home/wangwen_lab/zonghang/project/new_muxu_project/20.T2T/03.assembly_test/14.porec/02.hifiasm_hifi_ul_hic_utg/hifiasm_hic_ul_p_utg.fa
  cutter                     : DnpII

Output Options
  hi_c                       : true

Advanced Options
  threads                    : 19

4DN files Options
  mcool                      : true

Paired-end BAM Options
  paired_end                 : true
  paired_end_minimum_distance: 100
  paired_end_maximum_distance: 200

!! Only displaying parameters that differ from the pipeline defaults !!
--------------------------------------------------------------------------------
If you use epi2me-labs/wf-pore-c for your analysis please cite:

* The nf-core framework
  https://doi.org/10.1038/s41587-020-0439-x

--------------------------------------------------------------------------------
This is epi2me-labs/wf-pore-c v1.0.0-g265a1a4.
--------------------------------------------------------------------------------
Searching input for [.fastq, .fastq.gz, .fq, .fq.gz] files.
executor >  local (4)
[dc/0fee17] process > POREC:fastcat (1)                      [  0%] 0 of 1
[-        ] process > POREC:index_bam                        -
[08/0d9e07] process > POREC:prepare_genome:index_ref_mmi (1) [  0%] 0 of 1
[-        ] process > POREC:digest_align_annotate            -
[-        ] process > POREC:haplotag_alignments              -
[-        ] process > POREC:merge_coordsorted_bams           -
[-        ] process > POREC:merge_namesorted_bams            -
executor >  local (4)
[dc/0fee17] process > POREC:fastcat (1)                      [  0%] 0 of 1
[-        ] process > POREC:index_bam                        -
[08/0d9e07] process > POREC:prepare_genome:index_ref_mmi (1) [100%] 1 of 1, failed: 1 ✘
[-        ] process > POREC:digest_align_annotate            -
[-        ] process > POREC:haplotag_alignments              -
[-        ] process > POREC:merge_coordsorted_bams           -
[-        ] process > POREC:merge_namesorted_bams            -
[-        ] process > POREC:create_restriction_bed           -
[-        ] process > POREC:to_pairs_file                    -
[-        ] process > POREC:pairsToCooler                    -
[-        ] process > POREC:merge_mcools                     -
[-        ] process > POREC:merge_pairs                      -
[-        ] process > POREC:merge_pairs_stats                -
[-        ] process > POREC:pair_stats_report                -
[-        ] process > POREC:merge_paired_end_bams            -
[f9/bdeefa] process > POREC:getVersions                      [100%] 1 of 1 ✔
[f7/fb9e13] process > POREC:getParams                        [100%] 1 of 1 ✔
[-        ] process > POREC:makeReport                       -
[-        ] process > POREC:prepare_hic                      -
[-        ] process > output                                 -
ERROR ~ Error executing process > 'POREC:prepare_genome:index_ref_mmi (1)'

Caused by:
  Process `POREC:prepare_genome:index_ref_mmi (1)` terminated with an error exit status (137)

Command executed:

  minimap2 -x map-ont -d "reference.fasta.mmi" "reference.fasta"

Command exit status:
  137

Command output:  (empty)

Command error:
  [M::mm_idx_gen::173.163*1.62] collected minimizers
  .command.sh: line 2:    33 Killed                  minimap2 -x map-ont -d "reference.fasta.mmi" "reference.fasta"

Work dir:
  /public/home/wangwen_lab/zonghang/project/new_muxu_project/20.T2T/03.assembly_test/14.porec/02.hifiasm_hifi_ul_hic_utg/ul10.fq.gz.tmp/work/08/0d9e07be05828139553081644961eb

Tip: you can replicate the issue by changing to the process work dir and entering the command `bash .command.run`

 -- Check '.nextflow.log' file for details
WARN: Killing running tasks (1)
`

**Comment by cjw85** [comment]
Hi @socialhang,

Please reopen your issues using the Bug Report template and provide the requested information. Doing so really helps us to help you.

**Comment by socialhang** [comment]
ok, thanks!
