### ISSUE TITLE
digest_align_annotate step very slow and low cpu usage

### ISSUE THREAD

**Issue by ywang285** [epi2me-labs/wf-pore-c#45]
### Ask away!

Hi, I am new to nextflow and I found the digest_align_annotate step is very slow, even though I have 64 cpus and set --threads 64:

nextflow run epi2me-labs/wf-pore-c \
--fastq $Oak_DIR$Data_DIR/fastq_pass/allfastq.fastq.gz \
--threads 64 \
--ref $REFERENCE \
--cutter NlaIII \
--hi_c --mcool --paired_end \
-profile singularity \
--out_dir ${OUTPUT}

When I run the analysis using a windows version of EPI2ME, I found very low cpu usage (1 or 2 threads are 100% usage out of 128 threads in my computer during digest_align_annotate step). How should I increase the usage of cpus and speed up this step?

I also tried setting below parameters but did not improve cpu usage:
![image](https://github.com/epi2me-labs/wf-pore-c/assets/34822355/1d149717-cc41-48e1-9e7a-dbddfea9f7b1)

I found some questions mentioned --digest_annotate_threads and --ubam_map_threads, but I could not find any instructions about how to pass these parameters. Could you please let me know how to use more threads for digest_align_annotate step?

Thanks!

**Comment by ywang285** [comment]
I also tried to add -c .../my_config.cfg with below content, but it doesn't seem to improve the speed of digest_align_annotate
executor {
    $local {
        cpus = 64
        memory = "128 GB"
    }
}

**Comment by sarahjeeeze** [comment]
Hi, thanks for your question. you can just use the threads (`--threads`) parameter with a maximum number you want a process to use and the processes will calculate how many to use for minimap, python scripts etc. We simplified the various threads parameters down to one to make it more simple. Also - We have a fix coming in the next release that should reduce the disk space and memory required for this process.

**Comment by ywang285** [comment]
> Hi, thanks for your question. you can just use the threads (`--threads`) parameter with a maximum number you want a process to use and the processes will calculate how many to use for minimap, python scripts etc. We simplified the various threads parameters down to one to make it more simple. Also - We have a fix coming in the next release that should reduce the disk space and memory required for this process.

Thank you so much for your reply! 

To be clear, let's say I have 64 cpu and 256G memory to run the wf-pore-C:

In command line I use "--threads A"

In the config.cfg file, I use:
executor {
$local {
cpus = B
memory = "C GB"
}
}

What are the optimal A and B and C you would suggest me to put here?

**Comment by sarahjeeeze** [comment]
Maybe try A = 8, B = 64 and C = 128 - also use the latest version it it more computationally efficient

**Comment by ywang285** [comment]
> Maybe try A = 8, B = 64 and C = 128 - also use the latest version it it more computationally efficient

@sarahjeeeze Thank you so much for your reply! May I ask why not set C as full available RAM which is 256 GB?

**Comment by sarahjeeeze** [comment]
Oh because you have max 64 cpus and threads set to 8, that is max 8 processes that can run in parallel with approx 16gb ram per process = 128. But you could also give A = 4, B = 64 and C = 256  a go, if your chunk size is low (eg.20,000) that may be faster.

**Comment by sarahjeeeze** [comment]
Closing through lack of response
