### ISSUE TITLE
How to get percentage of Pore-C DNA?

### ISSUE THREAD

**Issue by jameson-orvis** [epi2me-labs/wf-pore-c#47]
### Ask away!

Hi,

Thank you for all your work on this lovely pipeline. Quick question, is the percentage of Pore-C DNA in a sample calculated somewhere in the pipeline? I have been asked this as a quality check, but I am not sure where this is located in the reports generated by the pipeline. Thanks!

**Comment by sarahjeeeze** [comment]
Hi, thanks for the feedback! Would you be able to clarify what you mean? The reads that are passed in to the workflow should all be pore-c reads?

**Comment by sarahjeeeze** [comment]
Closing through lack of response, feel free to re-open with a clarification of your question
