### ISSUE TITLE
Duplicate results in bam？

### ISSUE THREAD

**Issue by gotouerina** [epi2me-labs/wf-pore-c#48]
### Ask away!

When I convert bam to bed , I find results like this:
Bathyergus.bp.p_ctg.gfa_ptg000122l      28888261        28888741        1182eb83-9bdb-4b1b-921b-14ab366886f0:1188:1661/1        60      -
Bathyergus.bp.p_ctg.gfa_ptg000122l      28888261        28888741        1182eb83-9bdb-4b1b-921b-14ab366886f0:1188:1661/1        60      -
Bathyergus.bp.p_ctg.gfa_ptg000122l      28888261        28888741        1182eb83-9bdb-4b1b-921b-14ab366886f0:1188:1661/1        60      -
Bathyergus.bp.p_ctg.gfa_ptg000122l      28888261        28888741        1182eb83-9bdb-4b1b-921b-14ab366886f0:1188:1661/1        60      -
Bathyergus.bp.p_ctg.gfa_ptg000122l      28888261        28888741        1182eb83-9bdb-4b1b-921b-14ab366886f0:1188:1661/1        60      -
Bathyergus.bp.p_ctg.gfa_ptg000122l      28888261        28888741        1182eb83-9bdb-4b1b-921b-14ab366886f0:1188:1661/1        60      -
Bathyergus.bp.p_ctg.gfa_ptg000122l      28888261        28888741        1182eb83-9bdb-4b1b-921b-14ab366886f0:1188:1661/1        60      -
Bathyergus.bp.p_ctg.gfa_ptg000122l      28888261        28888741        1182eb83-9bdb-4b1b-921b-14ab366886f0:1188:1661/1        60      -
Bathyergus.bp.p_ctg.gfa_ptg000122l      28888261        28888741        1182eb83-9bdb-4b1b-921b-14ab366886f0:1188:1661/2        60      -
Bathyergus.bp.p_ctg.gfa_ptg000122l      28888261        28888741        1182eb83-9bdb-4b1b-921b-14ab366886f0:1188:1661/2        60      -
Bathyergus.bp.p_ctg.gfa_ptg000122l      28888261        28888741        1182eb83-9bdb-4b1b-921b-14ab366886f0:1188:1661/2        60      -
Bathyergus.bp.p_ctg.gfa_ptg000122l      28888261        28888741        1182eb83-9bdb-4b1b-921b-14ab366886f0:1188:1661/2        60      -
Bathyergus.bp.p_ctg.gfa_ptg000122l      28888261        28888741        1182eb83-9bdb-4b1b-921b-14ab366886f0:1188:1661/2        60      -
Bathyergus.bp.p_ctg.gfa_ptg000122l      28888261        28888741        1182eb83-9bdb-4b1b-921b-14ab366886f0:1188:1661/2        60      -
Bathyergus.bp.p_ctg.gfa_ptg000122l      28888261        28888741        1182eb83-9bdb-4b1b-921b-14ab366886f0:1188:1661/2        60      -
Bathyergus.bp.p_ctg.gfa_ptg000122l      28888261        28888741        1182eb83-9bdb-4b1b-921b-14ab366886f0:1188:1661/2        60      -
Bathyergus.bp.p_ctg.gfa_ptg000122l      28888261        28888741        1182eb83-9bdb-4b1b-921b-14ab366886f0:1188:1661/2        60      -
Bathyergus.bp.p_ctg.gfa_ptg000122l      28888261        28888741        1182eb83-9bdb-4b1b-921b-14ab366886f0:1188:1661/2        60      -
Bathyergus.bp.p_ctg.gfa_ptg000172l      2945179 2945508 1182eb83-9bdb-4b1b-921b-14ab366886f0:1661:1986/1        0       +
Bathyergus.bp.p_ctg.gfa_ptg000172l      2945179 2945508 1182eb83-9bdb-4b1b-921b-14ab366886f0:1661:1986/1        0       +
Bathyergus.bp.p_ctg.gfa_ptg000172l      2945179 2945508 1182eb83-9bdb-4b1b-921b-14ab366886f0:1661:1986/1        0       +
Bathyergus.bp.p_ctg.gfa_ptg000172l      2945179 2945508 1182eb83-9bdb-4b1b-921b-14ab366886f0:1661:1986/1        0       +
Bathyergus.bp.p_ctg.gfa_ptg000172l      2945179 2945508 1182eb83-9bdb-4b1b-921b-14ab366886f0:1661:1986/1        0       +
Bathyergus.bp.p_ctg.gfa_ptg000172l      2945179 2945508 1182eb83-9bdb-4b1b-921b-14ab366886f0:1661:1986/1        0       +
Bathyergus.bp.p_ctg.gfa_ptg000172l      2945179 2945508 1182eb83-9bdb-4b1b-921b-14ab366886f0:1661:1986/1        0       +
Bathyergus.bp.p_ctg.gfa_ptg000172l      2945179 2945508 1182eb83-9bdb-4b1b-921b-14ab366886f0:1661:1986/1        0       +
Bathyergus.bp.p_ctg.gfa_ptg000172l      2945179 2945508 1182eb83-9bdb-4b1b-921b-14ab366886f0:1661:1986/1        0       +
Bathyergus.bp.p_ctg.gfa_ptg000172l      2945179 2945508 1182eb83-9bdb-4b1b-921b-14ab366886f0:1661:1986/1        0       +
Bathyergus.bp.p_ctg.gfa_ptg000172l      2945179 2945508 1182eb83-9bdb-4b1b-921b-14ab366886f0:1661:1986/1        0       +

There are too many duplicate results . Should I remove the duplicate results by uniq for SALSA or Yahs?

**Comment by cjw85** [comment]
Please provide further details of how you have produced your files.

**Comment by gotouerina** [comment]
We used wf-pore-c for analysis, and get pair-end bam by  nextflow runwf-pore-c --fastq  B1.pass.fq.gz  --ref B.fasta --cutter NlaIII  -c increase_memory.config --threads 60 --paired_end_minimum_distance 100 --paired_end_maximum_distance 200  --chunk_size 10000 --paired_end -resume。 Then I convert the pair end bam to bed using bamTob, then sort -4 to sort.bed

**Comment by cjw85** [comment]
I believe what is being shown here is that you have a concatemer read with many sub-reads. When you convert the BAM to a BED you are seeing the name of one of the sub-reads but not its partner sub-read from the original concatemer read. This is expected.

Note there is a filter in the workflow, `--max_monomers` that can filter out concatemer reads with a large or excessive number of sub-reads.
