### ISSUE TITLE
Could I choose output?

### ISSUE THREAD

**Issue by gotouerina** [epi2me-labs/wf-pore-c#50]
### Ask away!

I wonder if you could plesae add a option to choose output file. In many situations, I  only want to scafflod and anchor a genome, but do not want to analysis the 3d-genome properties. So in many cases I do not want to see the bam files for they are too big to store in.

**Comment by sarahjeeeze** [comment]
Hi, you don't need to include all the parameters in the example, you can just add the --bed parameter for the bed file for the scaffolder tool which will avoid the very large paired end bam being created. It will still output the name and coord sorted BAMs though as they have to be generated to create the BAM and most users probably are interested in them.

**Comment by gotouerina** [comment]
> Hi, you don't need to include all the parameters in the example, you can just add the --bed parameter for the bed file for the scaffolder tool which will avoid the very large paired end bam being created. It will still output the name and coord sorted BAMs though as they have to be generated to create the BAM and most users probably are interested in them.

Thanks for your reply, I would try what you said.

**Comment by sarahjeeeze** [comment]
Closing through lack of response.
