### ISSUE TITLE
wf-pore-c-demo results confirmation

### ISSUE THREAD

**Issue by xinrjiang** [epi2me-labs/wf-pore-c#56]
### Ask away!

Hello, 
I'm run with the demo data using:
`nextflow run epi2me-labs/wf-pore-c \
--bam wf-pore-c-demo/porec_test.concatemers.bam --chunk_size 100 \
--ref wf-pore-c-demo/porec_test.fasta \
--cutter NlaIII \
--vcf wf-pore-c-demo/porec_test.phased_variants.vcf.gz \
--paired_end_minimum_distance 100 --paired_end_maximum_distance 200 --hi_c --mcool --paired_end \
-profile singularity`

and I want to know whether the file you put in the` test_data/tests.pairs.stats.txt` **_match_** the results of the demo data, because I gained the different `null.pairs.stats.txt` below:
`total   7447
total_unmapped  0
total_single_sided_mapped       1365
total_mapped    6082
total_dups      0
total_nodups    6082
cis     4358
trans   1724
pair_types/UN   686
pair_types/UU   6082
pair_types/NU   679
cis_1kb+        3060
cis_2kb+        1954
cis_4kb+        1289
cis_10kb+       0
cis_20kb+       0
cis_40kb+       0
summary/complexity_naive        nan
summary/frac_cis_10kb+  0.0
summary/frac_cis_1kb+   0.5031239723775074
summary/frac_dups       0.0
summary/frac_cis        0.7165406116409075
summary/frac_cis_40kb+  0.0
summary/frac_cis_2kb+   0.32127589608681356
summary/frac_cis_20kb+  0.0
summary/frac_cis_4kb+   0.21193686287405458
chrom_freq/chr2/chr1    836
chrom_freq/chr1/chr1    1022
chrom_freq/chr1/chr2    888
chrom_freq/chr2/chr2    3336
...`

Thanks.

**Comment by sarahjeeeze** [comment]
Closing
