### ISSUE TITLE
.pairs file full of empty or unaligned reads

### ISSUE THREAD

**Issue by hackkr** [epi2me-labs/wf-pore-c#60]
### Ask away!

Hello,

I am hoping for some clarification on the process for generating .pairs files. The workflow is running without errors on my machine, but the .pairs files are full of reads for which no fragments align (NN for all pairs of fragments in the read). This sample did contain the ONT control sequence, but shouldn't those reads be removed during the alignment process?

Here's an example of some of the reads in my file. 
```
#columns: readID chrom1 pos1 chrom2 pos2 strand1 strand2 pair_type walk_pair_index walk_pair_type mapq1 mapq2 pos51 pos52 pos31 pos32 cigar1 cigar2 read_len1 read_len2 matched_bp1 matched_bp2 algn_ref_span1 algn_ref_span2 algn_read_span1 algn_read_span2 dist_to_51 dist_to_52 dist_to_31 dist_to_32 mismatches1 mismatches2 rfrag1 rfrag_start1 rfrag_end1 rfrag2 rfrag_start2 rfrag_end2
86f3cccf-593e-43b3-abd6-36bac68ff01b	!	0	!	0	-	+	NN	1	R1	0	0	0	0	0	0	None	None	0	0	0	0	0	0	0	0	0	0	0	0			-1	0	0	-1	0	0
86f3cccf-593e-43b3-abd6-36bac68ff01b	!	0	!	0	-	+	NN	2	R1	0	0	0	0	0	0	None	None	0	0	0	0	0	0	0	0	0	0	0	0			-1	0	0	-1	0	0
86f3cccf-593e-43b3-abd6-36bac68ff01b	!	0	!	0	-	+	NN	3	R1	0	0	0	0	0	0	None	None	0	0	0	0	0	0	0	0	0	0	0	0			-1	0	0	-1	0	0
86f3cccf-593e-43b3-abd6-36bac68ff01b	!	0	!	0	-	+	NN	4	R1	0	0	0	0	0	0	None	None	0	0	0	0	0	0	0	0	0	0	0	0			-1	0	0	-1	0	0
86f3cccf-593e-43b3-abd6-36bac68ff01b	!	0	!	0	-	+	NN	5	R1	0	0	0	0	0	0	None	None	0	0	0	0	0	0	0	0	0	0	0	0			-1	0	0	-1	0	0
86f3cccf-593e-43b3-abd6-36bac68ff01b	!	0	!	0	-	+	NN	6	R1	0	0	0	0	0	0	None	None	0	0	0	0	0	0	0	0	0	0	0	0			-1	0	0	-1	0	0
86f3cccf-593e-43b3-abd6-36bac68ff01b	!	0	!	0	-	+	NN	7	R1	0	0	0	0	0	0	None	None	0	0	0	0	0	0	0	0	0	0	0	0			-1	0	0	-1	0	0
d01c3bd0-37a6-4046-ae6e-418524ac5c17	NC_017276.1	136162	NC_017276.1	128009	-	+	UU	1	R1	60	60	136162	128009	135891	128244	8M1D14M2D38M1D30M1I2M1I13M3D4M2D35M1D76M2I2M1D7M1I32M	6S91M1I38M1I32M1D4M1D7M1I2M2D30M2D26M	266	239	261	230	272	236	266	233	0	0	0	6			585	135893	136297	551	127985	128011
d01c3bd0-37a6-4046-ae6e-418524ac5c17	NC_017276.1	128244	NC_017276.1	136165	-	+	UU	2	R1	60	56	128244	136165	128009	136294	6S91M1I38M1I32M1D4M1D7M1I2M2D30M2D26M	2S75M3I8M1D46M28S	239	162	230	129	236	130	233	132	0	28	6	2			552	128011	128247	585	135893	136297
ab8e1d9d-9773-4a77-8b44-d56ffba42cb4	NC_017276.1	241177	!	0	-	+	UN	1	R1	60	0	241177	0	240571	0	3S12M1D68M1D20M1D92M1D59M1D89M2D5M1I10M1D9M111I18M1I60M3D8M2I9M1D10M1I2M1D6M1I19M2D4M1D8M2I51M3I32M	None	716	0	591	0	607	0	713	0	0	0	3	0			1047	240571	241180	-1	0	0
ab8e1d9d-9773-4a77-8b44-d56ffba42cb4	!	0	NC_017276.1	291993	-	+	NU	2	R1	0	60	0	291993	0	292555	None	90S24M3D10M1D79M2D65M1D9M1I6M2D16M1D11M1I55M1I4M1I86M1I65M1I43M4I3M1D11M1D50M2I14M33S	0	686	0	551	0	563	0	563	0	33	0	90			-1	0	0	1294	291941	292558
```

The 1st read contains 7 monomers of length 0, none of which map to my genome. The 2nd read is made up of 3 fragments mapping to positions 128009-128244, 135891-136162 and 136165-136294.  However, there are only 2 pairwise entries for the read (combination of 135891-136162 and 136165-136294 is missing). Is this indicative of an undigested site? I can't find any arguments in the documentation that suggest `parse2` automatically accounts for adjacent fragments.  The 3rd read contains only 2 monomers, but a UU interaction is not represented. 

Any assistance interpreting these results, or troubleshooting alignment steps would be much appreciated!

**Comment by sarahjeeeze** [comment]
However, there are only 2 pairwise entries for the read (combination of 135891-136162 and 136165-136294 is missing). Is this indicative of an undigested site? - yes could be undigested, as mentioned if there were adjacent fragments they should still be seperate records in the pairs file, although I will double check this is the case and get back to you. 
 
The 3rd read contains only 2 monomers, but a UU interaction is not represented. - The 3rd read is unique-null/null-unique because one side is not mapped `!	0	NC_017276.1	291993`

Let me know if further explanation needed or other questions, the pairs documentation may also be helpful - although apologies if you have already seen it https://pairtools.readthedocs.io/en/latest/stats.html
 https://pairtools.readthedocs.io/en/latest/formats.html#formats-for-storing-hi-c-pairs

**Comment by hackkr** [comment]
Thanks for you response! I guess I am struggling with what the junctions in the .pairs file output represent. It is *not* a description of the virtual pairwise interactions of all monomers in each read?

Using a read from the demo data,  
```
seqnames  start  end  width  strand  read_name  pass_filter  read_idx
chr2	537	5442	4906	*	CONCAT700	TRUE	1
chr2	1	537	537	*	CONCAT700	TRUE	1
chr2	6455	6538	84	*	CONCAT700	TRUE	1
chr2	6538	6764	227	*	CONCAT700	TRUE	1
```

```
readID  chrom1  pos1  chrom2  pos2  strand1  strand2  pair_type  walk_pair_index  walk_pair_type  mapq1  mapq2  pos51 
 pos52  pos31  pos32
CONCAT700	chr2	538	chr2	537	+	-	UU	1	R1	60	60	538	537	5442	1
CONCAT700	chr2	1	chr2	6538	+	-	UU	2	R1	60	51	1	6538	537	6456
CONCAT700	chr2	6456	chr2	6764	+	-	UU	3	R1	51	60	6456	6764	6538	6539
CONCAT700	chr2	6539	NA	0	+	+	UN	4	R1	60	0	6539	0	6764	0
```

**Comment by hackkr** [comment]
![pairtools_diagram](https://github.com/epi2me-labs/wf-pore-c/assets/36050332/622a50da-f106-4548-9134-7a069d2d075c)

Ah, I understand that these are relatively consistent results. I was confused by the strand assignment (forcing - for strand2 flips the orientation of pos52 and pos32). I still don't understand why the final UN pair is included? And this does not seem to represent a combinatorial expansion to all possible pairs of CONCAT700.

**Comment by hackkr** [comment]
Hello, do you have any suggestions for what to edit in the nextflow to get the combinatorial expansion? I'd like to see the contents of extract_pairs.tmp (line 20, 4nd.nf), before `pairtools restrict` is applied, but I am not sure where to look for that file in the auto generated `work/` directory.  thanks!

**Comment by sarahjeeeze** [comment]
Hi, to get the combinatorial expansion you can use the `--pairs` parameter output which will output a paired bam file and in the latest release these should be in the bed file, remove this line `rm -rf extract_pairs.tmp` if you want to see the extra_pairs.tmp file. It does increase run time and resource requirements considerably. You can filter pairs using parameters found in pore-c-py python package `https://github.com/epi2me-labs/pore-c-py/blob/master/pore_c_py/main.py` 

The parquet files should preserve the order of the monomers within the read, because of how the reads are processed.

**Comment by sarahjeeeze** [comment]
ah yes sorry `--paired_end`

**Comment by hackkr** [comment]
Hello, thanks for your help so far! I've generated a paired-end bams from `--paired_end` but am having trouble converting it to .cool format with various programs. Several that I've tried require separate bams for R1 and R2 reads (`hicpro` and `hicstuff`, for example).  I've tried splitting the file and name sorting with samtools, but run into errors. Pairtools + `cooler cload pairs` has also failed for me.

Could you please share more information about how the paired end bam is generated in the workflow and from what files?

**Comment by sarahjeeeze** [comment]
Hi, you can use the the `mcool` parameter in the workflow with default resolutions or specify resolutions with  `mcool_resolutions` parameter which will output a .cool file. I have some memory optimisations coming soon - let me know if you encounter any memory errors. We use cooler cload pairs in the workflow with these paramters - you can find the scripts in 4dn.nf file in the modules folder.
```cooler cload pairs -c1 2 -p1 3 -c2 4 -p2 5 ...```

Let me know if you need further guidance

**Comment by hackkr** [comment]
Thanks!

I've gotten it resolved but wanted to update here in case anyone else is trying to generate similar data. My goal was to generate a .mcool file of the Virtual Pairwise Contacts to compare with previously generated HiC data. The bam pairs in `--paired-end` output don't have the same readID, are not strand corrected to fit with paired-end expectations, and contain unaligned reads. This all makes it difficult to parse with Pairtools directly and get meaningful results. I also recommend verifying the sam flags present before filtering or splitting. 

After I updated the readIDs, I found `pairtools parse2 --report-position outer --report-orientation read` gave me what I wanted. That output then can be used to make a .cool file. 

For my samples, this process yielded ~841,000 UU pairs compared to ~322,000 UU pairs output by the workflow. My understanding is that the workflow `--pairs` output represents all sets of adjacent pairs in a read, but not all possible pairwise combinations of monomers in a read.

**Comment by sh0rt2l0ng** [comment]
Hi @hackkr , 

I am trying to do the same to get more pairs from the big "paired-end" bam. Could you please help clarify with some details how you did that? Thank you very much!

Hi @sarahjeeeze ,

Where could we find document on tags like Xw, MZ etc. in the "paired-end" bam? Thanks too!

**Comment by hackkr** [comment]
Hi @sh0rt2l0ng, here's the code I used to get virtual pairwise contacts. There are probably way more efficient ways to do this conversion, but I wanted to be able to check each step and this worked well enough for my purposes.

```
## Filter name sorted .bam file to contain proper, mapped pairs.
samtools view -hf 3 null.ns.bam > bams/ns-mapped.bam

## Split into forward and reverse reads, export as .sam to edit file names
samtools view -h -f 64 bams/ns-mapped.bam > bams/R1-mapped.sam
samtools view -h -f 128 bams/ns-mapped.bam > bams/R2-mapped.sam

## Check that number of reads in .sam files are the same & sum to reads in ns-mapped.bam:
echo '### merged .bam after filtering ###'
samtools flagstat bams/ns-mapped.bam
echo '### R1.bam ###'
samtools flagstat bams/R1-mapped.sam
echo '### R2.bam ###'
samtools flagstat bams/R2-mapped.sam

## Use regex to remove monomer ID (start and end pos) from read names. Append file line number (minus # of header lines) to read name to distinguish unique monomer pairs within each read.
awk '{sub(/:.*$/, ":"++c-7); print $1}' bams/R1-mapped.sam > pairnames-R1.txt
awk '{sub(/:.*$/, ":"++c-7); print $1}' bams/R2-mapped.sam > pairnames-R2.txt

## Names files should be identical for both R1 and R2:
cmp --silent pairnames-R1.txt pairnames-R2.txt && echo '### SUCCESS: modified names files are identical! ###' || echo '### WARNING: modified names files do NOT match! ###'
echo ''

## Replace first column of .sam files with updated read names
awk 'BEGIN {FS="\t"; OFS="\t"} FNR==NR{a[NR]=$1;next}{$1=a[FNR]}1' pairnames-R1.txt bams/R1-mapped.sam > bams/R1-renamed.sam
awk 'BEGIN {FS="\t"; OFS="\t"} FNR==NR{a[NR]=$1;next}{$1=a[FNR]}1' pairnames-R2.txt bams/R2-mapped.sam > bams/R2-renamed.sam

## Convert back into .bam files
samtools view -h bams/R1-renamed.sam > bams/R1-renamed.bam
samtools view -h bams/R2-renamed.sam > bams/R2-renamed.bam

## Remake name-sorted, merged file for pairtools parse2
samtools merge bams/R1_R2_renamed.bam bams/R1-renamed.bam bams/R2-renamed.bam 
samtools sort -n -o bams/R1_R2_renamed-ns.bam bams/R1_R2_renamed.bam

## Check that renamed .bams still have the same number of reads:
echo '### R1-renamed.bam ###'
samtools flagstat bams/R1-renamed.bam
echo ''
echo '### R2-renamed.bam ###'
samtools flagstat bams/R2-renamed.bam
echo ''

## Run pairtools parse2 to generate valid pairs file
pairtools parse2 \
--report-position outer --report-orientation read --add-pair-index --drop-seq --drop-sam \
--add-columns mapq,pos5,pos3,read_len,algn_ref_span,algn_read_span,mismatches,algn_idx,read_side \
--output-stats /PATH/to/vpc_mapped_stats.txt \
-c /PATH/to/sizes \
-o /PATH/to/vpc_mapped.pairs.gz \
/PATH/to/bams/R1_R2_renamed-ns.bam

## Sort & filter Pairsfile to contain only UU pairs
pairtools sort /PATH/to/vpc_mapped.pairs.gz -o /PATH/to/vpc_mapped_sorted.pairs.gz
pairtools select -o /PATH/to/vpc_mapped_sorted_UU.pairs.gz '(pair_type=="UU")' /PATH/to/vpc_mapped_sorted.pairs.gz

## convert to .cool (automatically flips reads)
cooler cload pairs -c1 2 -p1 3 -c2 4 -p2 5 /PATH/to/sizes:RESOLUTION \
/PATH/to/vpc_mapped_sorted_UU.pairs.gz \
/PATH/to/vpc_UU_1000.cool

## Make multiresolution cooler file
cooler zoomify -r 1000,2000,5000,10000,20000,50000,100000 -o /PATH/to/vpc_UU.mcool --balance ``--balance-args '--cis-only'`` /PATH/to/vpc_UU_1000.cool 
```

**Comment by sh0rt2l0ng** [comment]
Thank you very much @hackkr ! This is very helpful indeed.
