### ISSUE TITLE
how to run the workflow in HPC with Slurm scheduler and singularity

### ISSUE THREAD

**Issue by dnaase** [epi2me-labs/wf-pore-c#62]
### Ask away!

I can run the pipeline in one of the computer nodes in our HPC with -profile singularity. Since the files are large, I am wondering if it is possible to run the workflow with other profile (-profile) that enables the Slurm scheduler (with singularity container), so jobs can be submitted parallel to many computer nodes in our HPC?

thanks

**Comment by cjw85** [comment]
Please refer to the nextflow documentation for how to run our Nextflow workflows on an HPC cluster. You can provide an additional config file containing the configuration that you need.
