### ISSUE TITLE
How to run this pipeline without internet and root permission?

### ISSUE THREAD

**Issue by gotouerina** [epi2me-labs/wf-pore-c#65]
### Ask away!

Hello,

How can one use this pipeline without docker (root permission) and internet? I can not find the instructions.

I believed there should be a way to use singulairty and store the contained locally to do this, but I cannot solve it.

**Comment by sarahjeeeze** [comment]
Hey, you can use singularity and there is a good guide here with all the step i would of mention https://nf-co.re/docs/usage/getting_started/offline

**Comment by Blosers** [comment]
您好，请问您解决了该问题吗？我这边也没有办法进行同样的处理，所以可以请问一下我应该怎么做呢？谢谢。

**Comment by sarahjeeeze** [comment]
I don't have anything else to add than what is linked in that guide, closing through lack of response from original poster.
