### ISSUE TITLE
步骤报错

### ISSUE THREAD

**Issue by Blosers** [epi2me-labs/wf-pore-c#66]
### Ask away!

nextflow run epi2me-labs/wf-pore-c --help
Nextflow 24.04.3 is available - Please consider updating your version to it

 N E X T F L O W   ~  version 24.04.2

Launching `https://github.com/epi2me-labs/wf-pore-c` [spontaneous_shaw] DSL2 - revision: a4ffadaaa9 [master]

ERROR ~ Script compilation error
- file : /home/dingyuanhao/.nextflow/assets/epi2me-labs/wf-pore-c/main.nf
- cause: Invalid output definition @ line 386, column 5.
       output(POREC.out.stats)
       ^

1 error

 -- Check '.nextflow.log' file for details

老师您好，我每次按照您给的流程进行这样的操作都会出现这样的问题，请问该怎么解决？麻烦老师了，谢谢。

**Comment by sarahjeeeze** [comment]
Hi, we have a fix incoming for this- It is already in the prerelease `-r prerelease`
