### ISSUE TITLE
Filtering the bam of mapped fragments by MAPQ

### ISSUE THREAD

**Issue by Sean-McGinty** [epi2me-labs/wf-pore-c#67]
### Ask away!

As I understand it, the pipeline doesn't perform any kind of MAPQ filtering before generating the hic, pairs, or cooler files. What would be the easiest change I could make to this pipeline to filter out fragments with a low MAPQ before generation of the output files? If I am using singularity I wonder if making this change is even feasible. Any advice would be appreciated.

**Comment by sarahjeeeze** [comment]
Hi, if you are happy to ammend the script you can use something like `samtools view -bq ${minimum_mapping_quality} input.bam`

You could add that to the merge_name_sorted_bams/merge_coord_sorted_bams processes in modules/local/common.nf but we've not tested this and its not a supported feature currently.
