### ISSUE TITLE
I cannot execute wf-pore-c

### ISSUE THREAD

**Issue by Blosers** [epi2me-labs/wf-pore-c#75]
### Operating System

CentOS 7

### Workflow Version

wf-pore-c.sif   the latest

### Workflow Execution

Command line (Cluster)

### CLI command run

(base) [dingyuanhao@fat01 pore-c]$ cat pore-c.sh
#!/bin/bash
#SBATCH --job-name=pore-c
#SBATCH --partition=Par-2
#SBATCH --nodes=1
#SBATCH --ntasks-per-node=20
#SBATCH --error=/home/dingyuanhao/zxl_work/red_dwarf/DNPII/pore-c/pore-c.err
#SBATCH --output=/home/dingyuanhao/zxl_work/red_dwarf/DNPII/pore-c/pore-c.out

# 激活 Conda 环境（如果使用 Conda 管理 Nextflow 环境）
source ~/.bashrc
conda activate pore-c

nextflow run /home/dingyuanhao/zxl_software/wf-pore-c/wf-pore-c.sif  \
    --fastq '/home/dingyuanhao/zxl_work/red_dwarf/DNPII/pore-c/hic_data/E200004892_L01_95_1.fq.gz' \
    --chunk_size 10000 \
    --cutter DpnII \
    --hi_c \
    --mcool \
    --mcool_resolutions '1000,5000,10000,50000,100000,1000000' \
    --paired_end_maximum_distance 200 \
    --paired_end_minimum_distance 100 \
    --ref /home/dingyuanhao/zxl_work/red_dwarf/HA-T2T.fasta \
    -profile singularity

### Workflow Execution - CLI Execution Profile

None

### What happened?

After I submit the command pore-c.sh using sbatch, it always terminates after running for a few seconds. But based on the input result file, I don't know how to modify my own file. Perhaps there is a problem with the software I installed? I hope you can help me, thank you very much.

### Relevant log output

```shell
Aug-30 16:45:50.298 [main] DEBUG nextflow.cli.Launcher - $> nextflow run /home/dingyuanhao/zxl_software/wf-pore-c/wf-pore-c.sif --fastq /home/dingyuanhao/zxl_work/red_dwarf/DNPII/pore-c/hic_data/E200004892_L01_95_1.fq.gz --chunk_size 10000 --cutter DpnII --hi_c --mcool --mcool_resolutions 1000,5000,10000,50000,100000,1000000 --paired_end_maximum_distance 200 --paired_end_minimum_distance 100 --ref /home/dingyuanhao/zxl_work/red_dwarf/HA-T2T.fasta -profile singularity
Aug-30 16:45:50.512 [main] DEBUG nextflow.cli.CmdRun - N E X T F L O W  ~  version 24.04.4
Aug-30 16:45:50.540 [main] DEBUG nextflow.plugin.PluginsFacade - Setting up plugin manager > mode=prod; embedded=false; plugins-dir=/home/dingyuanhao/.nextflow/plugins; core-plugins: nf-amazon@2.5.3,nf-azure@1.6.1,nf-cloudcache@0.4.1,nf-codecommit@0.2.1,nf-console@1.1.3,nf-ga4gh@1.3.0,nf-google@1.13.2-patch1,nf-tower@1.9.1,nf-wave@1.4.2-patch1
Aug-30 16:45:50.638 [main] INFO  o.pf4j.DefaultPluginStatusProvider - Enabled plugins: []
Aug-30 16:45:50.639 [main] INFO  o.pf4j.DefaultPluginStatusProvider - Disabled plugins: []
Aug-30 16:45:50.643 [main] INFO  org.pf4j.DefaultPluginManager - PF4J version 3.12.0 in 'deployment' mode
Aug-30 16:45:50.658 [main] INFO  org.pf4j.AbstractPluginManager - No plugins
Aug-30 16:45:50.682 [main] DEBUG nextflow.config.ConfigBuilder - Found config base: /home/dingyuanhao/zxl_software/wf-pore-c/nextflow.config
Aug-30 16:45:50.686 [main] DEBUG nextflow.config.ConfigBuilder - Parsing config file: /home/dingyuanhao/zxl_software/wf-pore-c/nextflow.config
Aug-30 16:45:50.715 [main] DEBUG n.secret.LocalSecretsProvider - Secrets store: /home/dingyuanhao/.nextflow/secrets/store.json
Aug-30 16:45:50.719 [main] DEBUG nextflow.secret.SecretsLoader - Discovered secrets providers: [nextflow.secret.LocalSecretsProvider@601cbd8c] - activable => nextflow.secret.LocalSecretsProvider@601cbd8c
Aug-30 16:45:50.732 [main] DEBUG nextflow.config.ConfigBuilder - Applying config profile: `singularity`
Aug-30 16:45:51.512 [main] DEBUG nextflow.config.ConfigBuilder - Available config profiles: [standard, conda, singularity, awsbatch, local]
Aug-30 16:45:51.568 [main] ERROR nextflow.cli.Launcher - Input length = 1
java.nio.charset.MalformedInputException: Input length = 1
	at java.base/java.nio.charset.CoderResult.throwException(CoderResult.java:279)
	at java.base/sun.nio.cs.StreamDecoder.implRead(StreamDecoder.java:384)
	at java.base/sun.nio.cs.StreamDecoder.lockedRead(StreamDecoder.java:215)
	at java.base/sun.nio.cs.StreamDecoder.read(StreamDecoder.java:169)
	at java.base/java.io.InputStreamReader.read(InputStreamReader.java:188)
	at java.base/java.io.BufferedReader.read1(BufferedReader.java:223)
	at java.base/java.io.BufferedReader.implRead(BufferedReader.java:314)
	at java.base/java.io.BufferedReader.read(BufferedReader.java:296)
	at java.base/java.io.Reader.read(Reader.java:265)
	at org.codehaus.groovy.runtime.IOGroovyMethods.getText(IOGroovyMethods.java:862)
	at org.apache.groovy.nio.extensions.NioExtensions.getText(NioExtensions.java:400)
	at nextflow.cli.CmdRun.launchInfo(CmdRun.groovy:426)
	at nextflow.cli.CmdRun.run(CmdRun.groovy:331)
	at nextflow.cli.Launcher.run(Launcher.groovy:503)
	at nextflow.cli.Launcher.main(Launcher.groovy:657)
```

### Application activity log entry

```shell
(base) [dingyuanhao@fat01 pore-c]$ cat pore-c.out

 N E X T F L O W   ~  version 24.04.4

ERROR ~ Input length = 1

 -- Check '.nextflow.log' file for details
```

### Were you able to successfully run the latest version of the workflow with the demo data?

yes

**Comment by sarahjeeeze** [comment]
Hey, i am guessing by your other issue you got past this point? I don't think this `nextflow run /home/dingyuanhao/zxl_software/wf-pore-c/wf-pore-c.sif` is correct, you need to provide the sif `-with-singularity`

**Comment by Blosers** [comment]
Hello author, I still have some beginner's questions to ask. Please forgive me for my low level. How should I set - c increase_cemory.config, that is, what should I write in the increase_cemory.config file? Thank you very much for your answer.

**Comment by sarahjeeeze** [comment]
The default config should be fine for most cases - which you don't need to provide as its part of the workflow nextflow.config - are you running in to any errors? If so share the logs

**Comment by sarahjeeeze** [comment]
Closing through lack of response but feel free to re-open and share logs if you are still having trouble
