### ISSUE TITLE
Sequential pairing or all-to-all pairwise pairing before conversion to .hic?

### ISSUE THREAD

**Issue by Sean-McGinty** [epi2me-labs/wf-pore-c#77]
### Ask away!

Hello,
I had a question about how a read is resolved into pairwise contacts before conversion into .hic. 
For example, lets say we have a read with 5 fragments A,B,C,D,E.

I was under the impression that this read could form 10 (5 choose 2) pairwise interactions:
AB AC AD AE
      BC BD BE
            CD CE
                  DE
                  
When I look at the .pairs file this doesn't seem to be the case. I observe that a read with 5 fragments forms 4 interactions:
AB BC CD DE 
which would imply sequential pairing as opposed to all-to-all pairing.

![Screenshot 2024-09-12 at 12 01 46 PM](https://github.com/user-attachments/assets/58445dfc-bc54-4c3f-877f-64213fa841ad)

This figure from the original Pore-C paper implies there would be all to all pairing.

Could you please clarify this for me? Is the intended result all-to-all pairing of all fragments within or is it sequential pairing of fragments within a read?

Thankyou!

**Comment by sarahjeeeze** [comment]
Hi, yes it is just the representation in the pairtools file but your combinatorial expansion is the correct number of interactions - if you use the `--paired_end` parameter then the paired end BAM and bed file output will contain all combinations.

**Comment by sarahjeeeze** [comment]
Closing through lack of response.
