### ISSUE TITLE
bamstats invalid option

### ISSUE THREAD

**Issue by xinrjiang** [epi2me-labs/wf-pore-c#80]
### Ask away!

Hello authors! There is a question when I ran this workflow. 

I pulled the _.sif_ from docker hub (https://hub.docker.com/r/ontresearch/wf-pore-c) and I converted this into sif. Then, I modified the _process withLabel:wfporec_, _withLabel:pore_c_py_ and _withLabel:wf_common_'s container in _nextflow.config_ to be the PATH to my wf-pore-c.sif.

When I ran 
```nextflow
nextflow run main.nf -c nextflow.config --bam '../wf-pore-c-demo/porec_test.concatemers.bam' \
> --chunk_size 100 \
> --cutter 'NlaIII' \
> --hi_c \
> --mcool \
> --paired_end \
> --paired_end_maximum_distance 200 \
> --paired_end_minimum_distance 100 \
> --phased_vcf '../wf-pore-c-demo/porec_test.phased_variants.vcf.gz' \
> --ref '../wf-pore-c-demo/porec_test.fasta' \
> --vcf '../wf-pore-c-demo/porec_test.phased_variants.vcf.gz' \
> -profile singularity

 N E X T F L O W   ~  version 24.04.4

Launching `main.nf` [happy_carson] DSL2 - revision: 49bdae52d9


WARN: Found unexpected parameters:
* --phased_vcf: ../wf-pore-c-demo/porec_test.phased_variants.vcf.gz
- Ignore this warning: params.schema_ignore_params = "phased_vcf"


||||||||||   _____ ____ ___ ____  __  __ _____      _       _
||||||||||  | ____|  _ \_ _|___ \|  \/  | ____|    | | __ _| |__  ___
|||||       |  _| | |_) | |  __) | |\/| |  _| _____| |/ _` | '_ \/ __|
|||||       | |___|  __/| | / __/| |  | | |__|_____| | (_| | |_) \__ \
||||||||||  |_____|_|  |___|_____|_|  |_|_____|    |_|\__,_|_.__/|___/
||||||||||  wf-pore-c v1.3.0
--------------------------------------------------------------------------------
Core Nextflow options
  runName                    : happy_carson
  containerEngine            : singularity
  container                  : [withLabel:wfporec:/home/user/wf-pore-c.sif, withLabel:pore_c_py:/home/user/wf-pore-c.sif, withLabel:wf_common:/home/user/wf-pore-c.sif]
  launchDir                  : /home/user/wf-pore-c-1.3.0
  workDir                    : /home/user/wf-pore-c-1.3.0/work
  projectDir                 : /home/user/wf-pore-c-1.3.0
  userName                   : xrjiang
  profile                    : singularity
  configFiles                : /home/user/wf-pore-c-1.3.0/nextflow.config, /home/user/wf-pore-c-1.3.0/nextflow.config

Input Options
  bam                        : ../wf-pore-c-demo/porec_test.concatemers.bam
  ref                        : ../wf-pore-c-demo/porec_test.fasta
  vcf                        : ../wf-pore-c-demo/porec_test.phased_variants.vcf.gz

Output Options
  hi_c                       : true

Advanced Options
  chunk_size                 : 100

4DN files Options
  mcool                      : true

Paired-end BAM Options
  paired_end                 : true
  paired_end_minimum_distance: 100
  paired_end_maximum_distance: 200

!! Only displaying parameters that differ from the pipeline defaults !!
--------------------------------------------------------------------------------
If you use epi2me-labs/wf-pore-c for your analysis please cite:

* The nf-core framework
  https://doi.org/10.1038/s41587-020-0439-x


--------------------------------------------------------------------------------
This is epi2me-labs/wf-pore-c v1.3.0.
--------------------------------------------------------------------------------
Searching input for [.bam, .ubam] files.
executor >  local (6)
[50/3561cc] POREC:checkBamHeaders (1)              [100%] 1 of 1 ✔
[-        ] POREC:sortBam                          -
[-        ] POREC:mergeBams                        -
[-        ] POREC:catSortBams                      -
[-        ] POREC:validateIndex                    -
[32/13133d] POREC:samtools_index (1)               [100%] 1 of 1 ✔
[ad/99cb39] POREC:bamstats (1)                     [  0%] 0 of 1
[-        ] POREC:index_bam                        -
[c1/0ecdf9] POREC:prepare_genome:index_ref_mmi (1) [100%] 1 of 1 ✔
[-        ] POREC:digest_align_annotate            -
[-        ] POREC:haplotag_alignments              -
[-        ] POREC:merge_coordsorted_bams           -
[-        ] POREC:merge_namesorted_bams            -
[-        ] POREC:create_restriction_bed           -
[-        ] POREC:to_pairs_file                    -
[-        ] POREC:pairsToCooler                    -
[-        ] POREC:merge_mcools                     -
[-        ] POREC:merge_pairs                      -
[-        ] POREC:merge_pairs_stats                -
[-        ] POREC:pair_stats_report                -
[-        ] POREC:merge_paired_end_bams            -
[a3/749e23] POREC:getVersions                      [  0%] 0 of 1
[bb/4f59f3] POREC:getParams                        [100%] 1 of 1 ✔
[-        ] POREC:makeReport                       -
[-        ] POREC:prepare_hic                      -
executor >  local (6)
[50/3561cc] POREC:checkBamHeaders (1)              [100%] 1 of 1 ✔
[-        ] POREC:sortBam                          -
[-        ] POREC:mergeBams                        -
[-        ] POREC:catSortBams                      -
[-        ] POREC:validateIndex                    -
[32/13133d] POREC:samtools_index (1)               [100%] 1 of 1 ✔
[ad/99cb39] POREC:bamstats (1)                     [100%] 1 of 1, failed: 1 ✘
[-        ] POREC:index_bam                        -
[c1/0ecdf9] POREC:prepare_genome:index_ref_mmi (1) [100%] 1 of 1 ✔
[-        ] POREC:digest_align_annotate            -
[-        ] POREC:haplotag_alignments              -
[-        ] POREC:merge_coordsorted_bams           -
[-        ] POREC:merge_namesorted_bams            -
[-        ] POREC:create_restriction_bed           -
[-        ] POREC:to_pairs_file                    -
[-        ] POREC:pairsToCooler                    -
[-        ] POREC:merge_mcools                     -
[-        ] POREC:merge_pairs                      -
[-        ] POREC:merge_pairs_stats                -
[-        ] POREC:pair_stats_report                -
[-        ] POREC:merge_paired_end_bams            -
[a3/749e23] POREC:getVersions                      [  0%] 0 of 1
[bb/4f59f3] POREC:getParams                        [100%] 1 of 1 ✔
[-        ] POREC:makeReport                       -
[-        ] POREC:prepare_hic                      -
executor >  local (6)
[50/3561cc] POREC:checkBamHeaders (1)              [100%] 1 of 1 ✔
[-        ] POREC:sortBam                          -
[-        ] POREC:mergeBams                        -
[-        ] POREC:catSortBams                      -
[-        ] POREC:validateIndex                    -
[32/13133d] POREC:samtools_index (1)               [100%] 1 of 1 ✔
[ad/99cb39] POREC:bamstats (1)                     [100%] 1 of 1, failed: 1 ✘
[-        ] POREC:index_bam                        -
[c1/0ecdf9] POREC:prepare_genome:index_ref_mmi (1) [100%] 1 of 1 ✔
[-        ] POREC:digest_align_annotate            -
[-        ] POREC:haplotag_alignments              -
[-        ] POREC:merge_coordsorted_bams           -
[-        ] POREC:merge_namesorted_bams            -
[-        ] POREC:create_restriction_bed           -
[-        ] POREC:to_pairs_file                    -
[-        ] POREC:pairsToCooler                    -
[-        ] POREC:merge_mcools                     -
[-        ] POREC:merge_pairs                      -
[-        ] POREC:merge_pairs_stats                -
[-        ] POREC:pair_stats_report                -
[-        ] POREC:merge_paired_end_bams            -
[a3/749e23] POREC:getVersions                      [  0%] 0 of 1
[bb/4f59f3] POREC:getParams                        [100%] 1 of 1 ✔
[-        ] POREC:makeReport                       -
[-        ] POREC:prepare_hic                      -
[-        ] POREC:collectIngressResultsInDir       -
[-        ] POREC:get_filtered_out_bam             -
[-        ] publish                                -
ERROR ~ Error executing process > 'POREC:bamstats (1)'

Caused by:
  Process `POREC:bamstats (1)` terminated with an error exit status (64)


Command executed:

  mkdir bamstats_results
  bamstats reads.bam -s porec_test -u         -f bamstats_results/bamstats.flagstat.tsv -t 2         -i bamstats_results/bamstats.runids.tsv         -l bamstats_results/bamstats.basecallers.tsv         --histograms histograms      > /dev/null
  mv histograms/* bamstats_results/

  # get n_seqs from flagstats - need to sum them up
  awk 'NR==1{for (i=1; i<=NF; i++) {ix[$i] = i}} NR>1 {c+=$ix["total"]} END{print c}'         bamstats_results/bamstats.flagstat.tsv > bamstats_results/n_seqs
  # get unique run IDs (we add `-F '\t'` as `awk` uses any stretch of whitespace
  # as field delimiter otherwise and thus ignore empty columns)
  awk -F '\t' '
      NR==1 {for (i=1; i<=NF; i++) {ix[$i] = i}}
      # only print run_id if present
      NR>1 && $ix["run_id"] != "" {print $ix["run_id"]}
  ' bamstats_results/bamstats.runids.tsv | sort | uniq > bamstats_results/run_ids
  # get unique basecall models
  awk -F '\t' '
      NR==1 {for (i=1; i<=NF; i++) {ix[$i] = i}}
      # only print run_id if present
      NR>1 && $ix["basecaller"] != "" {print $ix["basecaller"]}
  ' bamstats_results/bamstats.basecallers.tsv | sort | uniq > bamstats_results/basecallers

Command exit status:
  64

Command output:
  (empty)

Command error:
  bamstats: invalid option -- 'i'
  Try `bamstats --help' or `bamstats --usage' for more information.

``` 
the question occurred. It seems that some dependencies version didn't match the workflow. I checked the report.html, the TASK POREC:getVersions also was aborted.

![report html screenshot](https://github.com/user-attachments/assets/5a22d622-321d-4063-9f00-83ce4530a574)

I don't know why this happened. Any advice would be appreciated.

**Comment by sarahjeeeze** [comment]
Hey, are you running it offline? If you pulled the sif? -  you also need the common singularity container if you are running offline https://hub.docker.com/r/ontresearch/wf-common

**Comment by Blosers** [comment]
老师您好，请问您这边可以正常运行wf-pore-c软件了吗？我这边还是没有办法正常运行，所以想请问一下该怎么样进行设置从而运行该软件？非常感谢您可以在百忙之中抽空解决一下我的问题，谢谢。

**Comment by Blosers** [comment]
老师您好，请问您的坚果可以正常运行wf-pore-c软件吗？我该坚果还是没有正常运行，所以想请问一下该进行怎样设置从而提高运行软件可以？非常感谢您在百忙求解抽空解决一下我的问题，谢谢。

**Comment by xinrjiang** [comment]
Hi @sarahjeeeze , I pulled all singulartiy containers again [https://hub.docker.com/r/ontresearch/wf-pore-c](url)  [https://hub.docker.com/r/ontresearch/wf-common](url) [https://hub.docker.com/r/ontresearch/pore-c-py](url)   but another question occurred.

`nextflow run epi2me-labs/wf-pore-c -c nextflow.config --bam '../wf-pore-c-demo/porec_test.concatemers.bam' --chunk_size 100 --cutter 'NlaIII' --hi_c --mcool --p                                                                                                                                                                                                                                      aired_end --paired_end_maximum_distance 200 --paired_end_minimum_distance 100 --phased_vcf '../wf-pore-c-demo/porec_test.phased_variants.vcf.gz' --ref '../wf-po                                                                                                                                                                                                                                      re-c-demo/porec_test.fasta' --vcf '../wf-pore-c-demo/porec_test.phased_variants.vcf.gz' -profile singularity

 N E X T F L O W   ~  version 24.04.4


Launching `https://github.com/epi2me-labs/wf-pore-c` [mighty_yonath] DSL2 - revision: 10caa387bc [master]


WARN: Found unexpected parameters:
* --phased_vcf: ../wf-pore-c-demo/porec_test.phased_variants.vcf.gz
- Ignore this warning: params.schema_ignore_params = "phased_vcf"


||||||||||   _____ ____ ___ ____  __  __ _____      _       _
||||||||||  | ____|  _ \_ _|___ \|  \/  | ____|    | | __ _| |__  ___
|||||       |  _| | |_) | |  __) | |\/| |  _| _____| |/ _` | '_ \/ __|
|||||       | |___|  __/| | / __/| |  | | |__|_____| | (_| | |_) \__ \
||||||||||  |_____|_|  |___|_____|_|  |_|_____|    |_|\__,_|_.__/|___/
||||||||||  wf-pore-c v1.3.0-g10caa38
--------------------------------------------------------------------------------
Core Nextflow options
  revision                   : master
  runName                    : mighty_yonath
  containerEngine            : singularity
  container                  : [withLabel:wfporec:/home/user/wf-pore-c.sif, withLabel:pore_c_py:/home/user/pore-c-py.sif, withLabel:wf                                                                                                                                                                                                                                      _common:/home/user/wf-common.sif]
  launchDir                  : /home/user/wf-pore-c-1.3.0
  workDir                    : /home/user/wf-pore-c-1.3.0/work
  projectDir                 : /home/user/.nextflow/assets/epi2me-labs/wf-pore-c
  userName                   : xrjiang
  profile                    : singularity
  configFiles                : /home/user/.nextflow/assets/epi2me-labs/wf-pore-c/nextflow.config, /home/user/wf-pore-c-1.3.0/nextflow.config, /h                                                                                                                                                                                                                                      ome/user/wf-pore-c-1.3.0/nextflow.config

Input Options
  bam                        : ../wf-pore-c-demo/porec_test.concatemers.bam
  ref                        : ../wf-pore-c-demo/porec_test.fasta
  vcf                        : ../wf-pore-c-demo/porec_test.phased_variants.vcf.gz

Output Options
  hi_c                       : true

Advanced Options
  chunk_size                 : 100

4DN files Options
  mcool                      : true

Paired-end BAM Options
  paired_end                 : true
  paired_end_minimum_distance: 100
  paired_end_maximum_distance: 200

!! Only displaying parameters that differ from the pipeline defaults !!
--------------------------------------------------------------------------------
If you use epi2me-labs/wf-pore-c for your analysis please cite:

* The nf-core framework
  https://doi.org/10.1038/s41587-020-0439-x


--------------------------------------------------------------------------------
This is epi2me-labs/wf-pore-c v1.3.0-g10caa38.
--------------------------------------------------------------------------------
Searching input for [.bam, .ubam] files.
executor >  local (61)
[99/407c99] POREC:checkBamHeaders (1)              [100%] 1 of 1 ✔
[-        ] POREC:sortBam                          -
[-        ] POREC:mergeBams                        -
[-        ] POREC:catSortBams                      -
[-        ] POREC:validateIndex                    -
[bd/c8d5e0] POREC:samtools_index (1)               [100%] 1 of 1 ✔
[9d/dc5ea7] POREC:bamstats (1)                     [100%] 1 of 1 ✔
[92/fd6107] POREC:index_bam (1)                    [100%] 1 of 1 ✔
[c6/6cb90c] POREC:prepare_genome:index_ref_mmi (1) [100%] 1 of 1 ✔
[78/558f6b] POREC:digest_align_annotate (2)        [100%] 11 of 11 ✔
[53/480452] POREC:haplotag_alignments (10)         [100%] 11 of 11 ✔
[96/68b13c] POREC:merge_coordsorted_bams (1)       [100%] 1 of 1 ✔
[b8/c0c8ab] POREC:merge_namesorted_bams (1)        [100%] 1 of 1 ✔
[9b/47baae] POREC:create_restriction_bed (1)       [100%] 1 of 1 ✔
[d8/68e941] POREC:to_pairs_file (8)                [100%] 11 of 11 ✔
[f1/61d01f] POREC:pairsToCooler (11)               [  0%] 0 of 11
[-        ] POREC:merge_mcools                     -
[4e/c7185d] POREC:merge_pairs (1)                  [  0%] 0 of 1
[0e/022da8] POREC:merge_pairs_stats (1)            [  0%] 0 of 1
[-        ] POREC:pair_stats_report                -
[41/3ddede] POREC:merge_paired_end_bams (1)        [100%] 1 of 1 ✔
[e7/902670] POREC:getVersions                      [100%] 1 of 1 ✔
[c0/08a268] POREC:getParams                        [100%] 1 of 1 ✔
[19/c6d422] POREC:makeReport                       [  0%] 0 of 1
[-        ] POREC:prepare_hic                      -
[68/c407ca] POREC:collectIngressResultsInDir (1)   [100%] 1 of 1 ✔
[87/79fa13] POREC:get_filtered_out_bam (1)         [100%] 1 of 1 ✔
[c6/f55569] publish (1)                            [100%] 1 of 1 ✔
ERROR ~ Error executing process > 'POREC:pairsToCooler (2)'

Caused by:
  Process `POREC:pairsToCooler (2)` terminated with an error exit status (1)


Command executed:

  cooler cload pairs -c1 2 -p1 3 -c2 4 -p2 5 fasta.fai:1000 porec_test.pairs.gz porec_test.pairs.cool

Command exit status:
  1

Command output:
  (empty)

Command error:
  INFO:cooler.create:Writing chunk 0: tmpelfx5kmm.multi.cool::0
  INFO:cooler.create:Creating cooler at "tmpelfx5kmm.multi.cool::/0"
  INFO:cooler.create:Writing chroms
  INFO:cooler.create:Writing bins
  INFO:cooler.create:Writing pixels
  INFO:cooler.create:Writing indexes
  INFO:cooler.create:Writing info
  INFO:cooler.create:Merging into porec_test.pairs.cool
  INFO:cooler.create:Creating cooler at "porec_test.pairs.cool::/"
  INFO:cooler.create:Writing chroms
  INFO:cooler.create:Writing bins
  INFO:cooler.create:Writing pixels
  INFO:cooler.reduce:nnzs: [0]
  INFO:cooler.reduce:current: [0]
  Traceback (most recent call last):
    File "/opt/custflow/epi2meuser/conda/bin/cooler", line 10, in <module>
      sys.exit(cli())
    File "/opt/custflow/epi2meuser/conda/lib/python3.8/site-packages/click/core.py", line 1157, in __call__
      return self.main(*args, **kwargs)
    File "/opt/custflow/epi2meuser/conda/lib/python3.8/site-packages/click/core.py", line 1078, in main
      rv = self.invoke(ctx)
    File "/opt/custflow/epi2meuser/conda/lib/python3.8/site-packages/click/core.py", line 1688, in invoke
      return _process_result(sub_ctx.command.invoke(sub_ctx))
    File "/opt/custflow/epi2meuser/conda/lib/python3.8/site-packages/click/core.py", line 1688, in invoke
      return _process_result(sub_ctx.command.invoke(sub_ctx))
    File "/opt/custflow/epi2meuser/conda/lib/python3.8/site-packages/click/core.py", line 1434, in invoke
      return ctx.invoke(self.callback, **ctx.params)
    File "/opt/custflow/epi2meuser/conda/lib/python3.8/site-packages/click/core.py", line 783, in invoke
      return __callback(*args, **kwargs)
    File "/opt/custflow/epi2meuser/conda/lib/python3.8/site-packages/cooler/cli/cload.py", line 584, in pairs
      create_cooler(
    File "/opt/custflow/epi2meuser/conda/lib/python3.8/site-packages/cooler/create/_create.py", line 1038, in create_cooler
      create_from_unordered(
    File "/opt/custflow/epi2meuser/conda/lib/python3.8/site-packages/cooler/create/_create.py", line 763, in create_from_unordered
      create(cool_uri, bins, chunks, columns=columns, dtypes=dtypes, mode=mode, **kwargs)
    File "/opt/custflow/epi2meuser/conda/lib/python3.8/site-packages/cooler/create/_create.py", line 641, in create
      nnz, ncontacts = write_pixels(
    File "/opt/custflow/epi2meuser/conda/lib/python3.8/site-packages/cooler/create/_create.py", line 211, in write_pixels
      for i, chunk in enumerate(iterable):
    File "/opt/custflow/epi2meuser/conda/lib/python3.8/site-packages/cooler/reduce.py", line 151, in __iter__
      combined = pd.concat(
    File "/opt/custflow/epi2meuser/conda/lib/python3.8/site-packages/pandas/util/_decorators.py", line 331, in wrapper
      return func(*args, **kwargs)
    File "/opt/custflow/epi2meuser/conda/lib/python3.8/site-packages/pandas/core/reshape/concat.py", line 368, in concat
      op = _Concatenator(
    File "/opt/custflow/epi2meuser/conda/lib/python3.8/site-packages/pandas/core/reshape/concat.py", line 425, in __init__
      raise ValueError("No objects to concatenate")
  ValueError: No objects to concatenate

Work dir:
  /home/user/work/9e/182888fd179372acaf215ab26eb8f7

Tip: you can try to figure out what's wrong by changing to the process work dir and showing the script file named `.command.sh`

 -- Check '.nextflow.log' file for details`

**Comment by xinrjiang** [comment]
Hi @sarahjeeeze  , thank you for last reply. I pulled all singulartiy containers again [https://hub.docker.com/r/ontresearch/wf-pore-c](https://github.com/epi2me-labs/wf-pore-c/issues/url),  [https://hub.docker.com/r/ontresearch/wf-common](https://github.com/epi2me-labs/wf-pore-c/issues/url) and [https://hub.docker.com/r/ontresearch/pore-c-py](https://github.com/epi2me-labs/wf-pore-c/issues/url) but another question occurred.

```nextflow
nextflow run epi2me-labs/wf-pore-c -c nextflow.config --bam '../wf-pore-c-demo/porec_test.concatemers.bam' --chunk_size 100 --cutter 'NlaIII' --hi_c --mcool --p aired_end --paired_end_maximum_distance 200 --paired_end_minimum_distance 100 --phased_vcf '../wf-pore-c-demo/porec_test.phased_variants.vcf.gz' --ref '../wf-po re-c-demo/porec_test.fasta' --vcf '../wf-pore-c-demo/porec_test.phased_variants.vcf.gz' -profile singularity

N E X T F L O W ~ version 24.04.4

Launching https://github.com/epi2me-labs/wf-pore-c [mighty_yonath] DSL2 - revision: https://github.com/epi2me-labs/wf-pore-c/commit/10caa387bc5f75be324568712c82bc8801ea1b71 [master]

WARN: Found unexpected parameters:

--phased_vcf: ../wf-pore-c-demo/porec_test.phased_variants.vcf.gz
Ignore this warning: params.schema_ignore_params = "phased_vcf"
|||||||||| _____ ____ ___ ____ __ __ _____ _ _
|||||||||| | | _ _ | | / | | | | __ | | ___
||||| | | | |) | | __) | |/| | | _| |/ ` | ' / |
||||| | || /| | / /| | | | ||| | (| | |) _
|||||||||| |_____|| |||| ||| ||_,|./|__/
|||||||||| wf-pore-c v1.3.0-g10caa38
Core Nextflow options
revision : master
runName : mighty_yonath
containerEngine : singularity
container : [withLabel:wfporec:/home/user/wf-pore-c.sif, withLabel:pore_c_py:/home/user/pore-c-py.sif, withLabel:wf _common:/home/user/wf-common.sif]
launchDir : /home/user
workDir : /home/user/work
projectDir : /home/user/.nextflow/assets/epi2me-labs/wf-pore-c
userName : user
profile : singularity
configFiles : /home/user/.nextflow/assets/epi2me-labs/wf-pore-c/nextflow.config, /home/user/wf-pore-c-1.3.0/nextflow.config, /h ome/user/wf-pore-c-1.3.0/nextflow.config

Input Options
bam : ../wf-pore-c-demo/porec_test.concatemers.bam
ref : ../wf-pore-c-demo/porec_test.fasta
vcf : ../wf-pore-c-demo/porec_test.phased_variants.vcf.gz

Output Options
hi_c : true

Advanced Options
chunk_size : 100

4DN files Options
mcool : true

Paired-end BAM Options
paired_end : true
paired_end_minimum_distance: 100
paired_end_maximum_distance: 200

!! Only displaying parameters that differ from the pipeline defaults !!
If you use epi2me-labs/wf-pore-c for your analysis please cite:

The nf-core framework
https://doi.org/10.1038/s41587-020-0439-x
This is epi2me-labs/wf-pore-c v1.3.0-g10caa38.
Searching input for [.bam, .ubam] files.
executor > local (61)
[99/407c99] POREC:checkBamHeaders (1) [100%] 1 of 1 ✔
[- ] POREC:sortBam -
[- ] POREC:mergeBams -
[- ] POREC:catSortBams -
[- ] POREC:validateIndex -
[bd/c8d5e0] POREC:samtools_index (1) [100%] 1 of 1 ✔
[9d/dc5ea7] POREC:bamstats (1) [100%] 1 of 1 ✔
[92/fd6107] POREC:index_bam (1) [100%] 1 of 1 ✔
[c6/6cb90c] POREC:prepare_genome:index_ref_mmi (1) [100%] 1 of 1 ✔
[78/558f6b] POREC:digest_align_annotate (2) [100%] 11 of 11 ✔
[53/480452] POREC:haplotag_alignments (10) [100%] 11 of 11 ✔
[96/68b13c] POREC:merge_coordsorted_bams (1) [100%] 1 of 1 ✔
[b8/c0c8ab] POREC:merge_namesorted_bams (1) [100%] 1 of 1 ✔
[9b/47baae] POREC:create_restriction_bed (1) [100%] 1 of 1 ✔
[d8/68e941] POREC:to_pairs_file (8) [100%] 11 of 11 ✔
[f1/61d01f] POREC:pairsToCooler (11) [ 0%] 0 of 11
[- ] POREC:merge_mcools -
[4e/c7185d] POREC:merge_pairs (1) [ 0%] 0 of 1
[0e/022da8] POREC:merge_pairs_stats (1) [ 0%] 0 of 1
[- ] POREC:pair_stats_report -
[41/3ddede] POREC:merge_paired_end_bams (1) [100%] 1 of 1 ✔
[e7/902670] POREC:getVersions [100%] 1 of 1 ✔
[c0/08a268] POREC:getParams [100%] 1 of 1 ✔
[19/c6d422] POREC:makeReport [ 0%] 0 of 1
[- ] POREC:prepare_hic -
[68/c407ca] POREC:collectIngressResultsInDir (1) [100%] 1 of 1 ✔
[87/79fa13] POREC:get_filtered_out_bam (1) [100%] 1 of 1 ✔
[c6/f55569] publish (1) [100%] 1 of 1 ✔
ERROR ~ Error executing process > 'POREC:pairsToCooler (2)'

Caused by:
Process POREC:pairsToCooler (2) terminated with an error exit status (1)

Command executed:

cooler cload pairs -c1 2 -p1 3 -c2 4 -p2 5 fasta.fai:1000 porec_test.pairs.gz porec_test.pairs.cool

Command exit status:
1

Command output:
(empty)

Command error:
INFO:cooler.create:Writing chunk 0: tmpelfx5kmm.multi.cool::0
INFO:cooler.create:Creating cooler at "tmpelfx5kmm.multi.cool::/0"
INFO:cooler.create:Writing chroms
INFO:cooler.create:Writing bins
INFO:cooler.create:Writing pixels
INFO:cooler.create:Writing indexes
INFO:cooler.create:Writing info
INFO:cooler.create:Merging into porec_test.pairs.cool
INFO:cooler.create:Creating cooler at "porec_test.pairs.cool::/"
INFO:cooler.create:Writing chroms
INFO:cooler.create:Writing bins
INFO:cooler.create:Writing pixels
INFO:cooler.reduce:nnzs: [0]
INFO:cooler.reduce:current: [0]
Traceback (most recent call last):
File "/opt/custflow/epi2meuser/conda/bin/cooler", line 10, in
sys.exit(cli())
File "/opt/custflow/epi2meuser/conda/lib/python3.8/site-packages/click/core.py", line 1157, in call
return self.main(*args, **kwargs)
File "/opt/custflow/epi2meuser/conda/lib/python3.8/site-packages/click/core.py", line 1078, in main
rv = self.invoke(ctx)
File "/opt/custflow/epi2meuser/conda/lib/python3.8/site-packages/click/core.py", line 1688, in invoke
return _process_result(sub_ctx.command.invoke(sub_ctx))
File "/opt/custflow/epi2meuser/conda/lib/python3.8/site-packages/click/core.py", line 1688, in invoke
return _process_result(sub_ctx.command.invoke(sub_ctx))
File "/opt/custflow/epi2meuser/conda/lib/python3.8/site-packages/click/core.py", line 1434, in invoke
return ctx.invoke(self.callback, **ctx.params)
File "/opt/custflow/epi2meuser/conda/lib/python3.8/site-packages/click/core.py", line 783, in invoke
return __callback(*args, **kwargs)
File "/opt/custflow/epi2meuser/conda/lib/python3.8/site-packages/cooler/cli/cload.py", line 584, in pairs
create_cooler(
File "/opt/custflow/epi2meuser/conda/lib/python3.8/site-packages/cooler/create/_create.py", line 1038, in create_cooler
create_from_unordered(
File "/opt/custflow/epi2meuser/conda/lib/python3.8/site-packages/cooler/create/_create.py", line 763, in create_from_unordered
create(cool_uri, bins, chunks, columns=columns, dtypes=dtypes, mode=mode, **kwargs)
File "/opt/custflow/epi2meuser/conda/lib/python3.8/site-packages/cooler/create/_create.py", line 641, in create
nnz, ncontacts = write_pixels(
File "/opt/custflow/epi2meuser/conda/lib/python3.8/site-packages/cooler/create/_create.py", line 211, in write_pixels
for i, chunk in enumerate(iterable):
File "/opt/custflow/epi2meuser/conda/lib/python3.8/site-packages/cooler/reduce.py", line 151, in iter
combined = pd.concat(
File "/opt/custflow/epi2meuser/conda/lib/python3.8/site-packages/pandas/util/_decorators.py", line 331, in wrapper
return func(*args, **kwargs)
File "/opt/custflow/epi2meuser/conda/lib/python3.8/site-packages/pandas/core/reshape/concat.py", line 368, in concat
op = _Concatenator(
File "/opt/custflow/epi2meuser/conda/lib/python3.8/site-packages/pandas/core/reshape/concat.py", line 425, in init
raise ValueError("No objects to concatenate")
ValueError: No objects to concatenate

Work dir:
/home/user/work/9e/182888fd179372acaf215ab26eb8f7

Tip: you can try to figure out what's wrong by changing to the process work dir and showing the script file named .command.sh

-- Check '.nextflow.log' file for details
``` 

How could we solve this problem? Any suggestions would be greatly appreciated.

**Comment by Blosers** [comment]
老师您好，请问您是如何解决在线运行的问题，我已经下载了wf-pore-c.sif文件到本地，也在我的nextflow.contig文件中修改了withLabel:wfporec、withLabel:pore_c_py和withLabel:wf_common，但是依旧没有办法在本地运行，每一次报错都是网络连接存在问题。任何建议都将不胜感激，麻烦老师了。谢谢。

**Comment by Blosers** [comment]
Hello teacher, may I ask for the files wf-pore-comm.sif and wf-pore-c-py.sif from you? I really can't download it, sorry. Thank you very much for your help.

**Comment by SamStudio8** [comment]
@xinrjiang If you have new issues, could you kindly open a new Bug Report?
