### ISSUE TITLE
Offline operation wf-pore-c

### ISSUE THREAD

**Issue by Blosers** [epi2me-labs/wf-pore-c#82]
### Operating System

Ubuntu 22.04

### Workflow Version

wf-pore-c.sif   the latest

### Workflow Execution

Command line (Cluster)

### CLI command run

#!/bin/bash
#SBATCH --job-name=pore-c
#SBATCH --partition=Par-1
#SBATCH --nodes=1
#SBATCH --ntasks-per-node=20
#SBATCH --error=/home/dingyuanhao/zxl_work/red_dwarf/wf-pore-c/pore-c.err
#SBATCH --output=/home/dingyuanhao/zxl_work/red_dwarf/wf-pore-c/pore-c.out

## Execute your command

source ~/.bashrc

conda activate pore-c

nextflow run /home/dingyuanhao/zxl_software/wf-pore-c/ \
      --bam '/home/dingyuanhao/zxl_software/wf-pore-c/test_data/porec_test.concatemers.bam' \
      --chunk_size 100 \
      --cutter 'NlaIII' \
      --hi_c \
      --mcool \
      --paired_end \
      --paired_end_maximum_distance 200 \
      --paired_end_minimum_distance 100 \
      --phased_vcf '/home/dingyuanhao/zxl_software/wf-pore-c/test_data/porec_test.phased_variants.vcf.gz' \
      --ref '/home/dingyuanhao/zxl_software/wf-pore-c/test_data/porec_test.fasta' \
      --vcf '/home/dingyuanhao/zxl_software/wf-pore-c/test_data/porec_test.phased_variants.vcf.gz' \
      -profile singularity \
      -c /home/dingyuanhao/zxl_software/wf-pore-c/nextflow.config

### Workflow Execution - CLI Execution Profile

singularity

### What happened?

cat nextflow.contig
//
// Notes to End Users.
//
// The workflow should run without editing this configuration file,
// however there may be instances in which you wish to edit this
// file for compute performance or other reasons. Please see:
//
//   https://nextflow.io/docs/latest/config.html#configuration
//
// for further help editing this file.

params {
    help = false
    version = false
    bam = null
    fastq = null
    ref = null
    cutter = 'NlaIII'
    out_dir = 'output'
    chunk_size = 20000
    sample = null
    vcf = null
    pairs = false
    mcool = false
    mcool_resolutions = '1000,2000,5000N' // 4DN tuple default
    coverage = false

    minimap2_settings = '-x map-ont'
    threads = 4

    aws_image_prefix = null
    aws_queue = null
    disable_ping = false

    analyse_unclassified = false
    monochrome_logs = false
    validate_params = true
    show_hidden_params = false
    schema_ignore_params = 'show_hidden_params,validate_params,monochrome_logs,aws_queue,aws_image_prefix,wf'
    chromunity = false
    chromunity_merge_distance = -1
    cool_bin_size = 1000
    paired_end = false
    summary_json = true
    filter_pairs = false
    paired_end_minimum_distance = -1
    paired_end_maximum_distance = -1
    sample_sheet = null
    hi_c = false
    bed = false
    pairtools_chunksize = 100000
    max_monomers = 250

    wf {
        name = 'wf-pore-c'
        example_cmd = [
            "--bam 'wf-pore-c-demo/porec_test.concatemers.bam'",
            "--chunk_size 100",
            "--cutter 'NlaIII'",
            "--hi_c",
            "--mcool",
            "--paired_end",
            "--paired_end_maximum_distance 200",
            "--paired_end_minimum_distance 100",
            "--phased_vcf 'wf-pore-c-demo/porec_test.phased_variants.vcf.gz'",
            "--ref 'wf-pore-c-demo/porec_test.fasta'",
            "--vcf 'wf-pore-c-demo/porec_test.phased_variants.vcf.gz'",
        ]
        common_sha = "shad399cf22079b5b153920ac39ee40095a677933f1"
        container_sha = 'sha3787c234c0cacf66a67fb77da223cc2e1cb0baf0'
        pore_c_py_sha = 'sha50378db56ddafe19f5e1d313ddb52dc70bbcc2bd'
        agent = null
    }
}

manifest {
    name            = 'epi2me-labs/wf-pore-c'
    author          = 'Oxford Nanopore Technologies'
    homePage        = 'https://github.com/epi2me-labs/wf-pore-c'
    description     = 'workflow for analysing pore-c data.'
    mainScript      = 'main.nf'
    nextflowVersion = '>=23.04.2'
    version         = 'v1.2.2'
}

epi2melabs {
  tags = "pore-c,contact,map,chromatin,conformation,capture"
}

// used by default for "standard" (docker) and singularity profiles,
// other profiles may override.
process {
    withLabel:wfporec {
        container = "home/dingyuanhao/zxl_software/wf-pore-c/wf-pore-c.sif"
    }
    withLabel:pore_c_py {
        container = "/home/dingyuanhao/zxl_software/wf-pore-c/pore-c-py.sif"
    }
    withLabel:wf_common {
        container = "/home/dingyuanhao/zxl_software/wf-pore-c/wf-common.sif"
    }
    shell = ['/bin/bash', '-euo', 'pipefail']
    withName: "merge_coordsorted_bams|merge_namesorted_bams" {
        publishDir = [
            path: { "${params.out_dir}/bams/" },
            mode: "copy",
            pattern: '*.{bam,csi,bai}'
        ]
    }
    withName: "merge_pairs|merge_pairs_stats|merge_mcools|create_restriction_bed|pair_stats_report" {
        publishDir = [
            path: { "${params.out_dir}/pairs/" },
            mode: "copy",
            pattern: '*.{gz,stats.txt,bed,mcool,html}'
        ]
    }
    withName: "mosdepth_coverage" {
        publishDir = [
            path: { "${params.out_dir}/coverage/" },
            mode: "copy",
            pattern: '*.*'
        ]
    }
    withName: "merge_parquets_to_dataset" {
        publishDir = [
            path: { "${params.out_dir}/chromunity/" },
            mode: "copy",
            pattern: '*.*'
        ]
    }
    withName: "merge_paired_end_bams" {
        publishDir = [
            path: { "${params.out_dir}/paired_end/" },
            mode: "copy",
            pattern: '*.{bam,csi,bai}'
        ]
    }
    withName: "makeReport" {
        publishDir = [
            path: { "${params.out_dir}/" },
            mode: "copy",
            pattern: '*.{html}'
        ]
    }
    withName: "prepare_hic" {
        publishDir = [
            path: { "${params.out_dir}/hi-c" },
            mode: "copy",
            pattern: '*.{hic}'
        ]
    }
    withName: "mergeBed" {
        publishDir = [
            path: { "${params.out_dir}/bed" },
            mode: "copy",
            pattern: '*.{bed}'
        ]
    }
    withName: "get_filtered_out_bam" {
        publishDir = [
            path: { "${params.out_dir}/filtered_out" },
            mode: "copy",
            pattern: '*.{bam}'
        ]
    }
}

profiles {
    // the "standard" profile is used implicitely by nextflow
    // if no other profile is given on the CLI
    standard {
        docker {
            enabled = true
            // this ensures container is run as host user and group, but
            //    also adds host user to the within-container group
            runOptions = "--user \$(id -u):\$(id -g) --group-add 100"
        }
    }

    // using singularity instead of docker
    singularity {
        process {
            executor = 'local'
            // 指定本地 Singularity 镜像的路径
            container = 'singularity:///home/dingyuanhao/zxl_software/wf-pore-c/wf-pore-c.sif'
        }
        singularity {
            enabled = true
            autoMounts = true
        }
    }

    // keep stub conda profile to prevent unknown profile warning so users get a better error
    conda {
        conda.enabled = true
    }

    // Using AWS batch.
    // May need to set aws.region and aws.batch.cliPath
    awsbatch {
        process {
            executor = 'awsbatch'
            queue = "${params.aws_queue}"
            memory = '8G'
            withLabel:wfporec {
                container = "/home/dingyuanhao/zxl_software/wf-pore-c/wf-pore-c.sif"
            }
            withLabel:pore_c_py {
                 container = "/home/dingyuanhao/zxl_software/wf-pore-c/pore-c-py.sif"
            }
            withLabel:wf_common {
                container = "/home/dingyuanhao/zxl_software/wf-pore-c/wf-common.sif"
            }
            shell = ['/bin/bash', '-euo', 'pipefail']
        }
    }
    aws.region = 'eu-west-1'
    aws.batch.cliPath = '/home/ec2-user/miniconda/bin/aws'

    // local profile for simplified development testing
    local {
        process.executor = 'local'
    }
}

timeline {
  enabled = true
  overwrite = true
  file = "${params.out_dir}/execution/timeline.html"
}
report {
  enabled = true
  overwrite = true
  file = "${params.out_dir}/execution/report.html"
}
trace {
  enabled = true
  overwrite = true
  file = "${params.out_dir}/execution/trace.txt"
}

env {
    PYTHONNOUSERSITE = 1
    JAVA_TOOL_OPTIONS = "-Xlog:disable -Xlog:all=warning:stderr"
}

###error

Plus 7 more processes waiting for tasks…
ERROR ~ Error executing process > 'POREC:index_bam (1)'

Caused by:
  Failed to pull singularity image
    command: singularity pull  --name home-dingyuanhao-zxl_software-wf-pore-c-wf-pore-c.sif.pulling.1729494354443 docker://home/dingyuanhao/zxl_software/wf-pore-c/wf-pore-c.sif > /dev/null
    status : 255
    hint   : Try and increase singularity.pullTimeout in the config (current is "20m")
    message:
      [31mFATAL:   While making image from oci registry: failed to get checksum for docker://home/dingyuanhao/zxl_software/wf-pore-c/wf-pore-c.sif: pinging docker registry returned: Get "https://registry-1.docker.io/v2/": dial tcp 103.200.30.143:443: i/o timeout

 -- Check '.nextflow.log' file for details

I think I have already configured local running in the NextFlow.dentig file, but why is the network still being pulled? Is there any problem with my offline running configuration in the NextFlow.dentig file?

### Relevant log output

```shell
N E X T F L O W   ~  version 24.04.4

Launching `/home/dingyuanhao/zxl_software/wf-pore-c/main.nf` [sleepy_lumiere] DSL2 - revision: 8c2550bad6


WARN: Found unexpected parameters:
* --phased_vcf: /home/dingyuanhao/zxl_software/wf-pore-c/test_data/porec_test.phased_variants.vcf.gz
- Ignore this warning: params.schema_ignore_params = "phased_vcf"


||||||||||   _____ ____ ___ ____  __  __ _____      _       _
||||||||||  | ____|  _ \_ _|___ \|  \/  | ____|    | | __ _| |__  ___
|||||       |  _| | |_) | |  __) | |\/| |  _| _____| |/ _` | '_ \/ __|
|||||       | |___|  __/| | / __/| |  | | |__|_____| | (_| | |_) \__ \
||||||||||  |_____|_|  |___|_____|_|  |_|_____|    |_|\__,_|_.__/|___/
||||||||||  wf-pore-c v1.2.2
--------------------------------------------------------------------------------
Core Nextflow options
  runName                    : sleepy_lumiere
  containerEngine            : singularity
  container                  : [withLabel:wfporec:home/dingyuanhao/zxl_software/wf-pore-c/wf-pore-c.sif, withLabel:pore_c_py:/home/dingyuanhao/zxl_software/wf-pore-c/pore-c-py.sif, withLabel:wf_common:/home/dingyuanhao/zxl_software/wf-pore-c/wf-common.sif, default:singularity:///home/dingyuanhao/zxl_software/wf-pore-c/wf-pore-c.sif]
  launchDir                  : /home/dingyuanhao/zxl_work/red_dwarf/wf-pore-c
  workDir                    : /home/dingyuanhao/zxl_work/red_dwarf/wf-pore-c/work
  projectDir                 : /home/dingyuanhao/zxl_software/wf-pore-c
  userName                   : dingyuanhao
  profile                    : singularity
  configFiles                : /home/dingyuanhao/zxl_software/wf-pore-c/nextflow.config, /home/dingyuanhao/zxl_software/wf-pore-c/nextflow.config

Input Options
  bam                        : /home/dingyuanhao/zxl_software/wf-pore-c/test_data/porec_test.concatemers.bam
  ref                        : /home/dingyuanhao/zxl_software/wf-pore-c/test_data/porec_test.fasta
  vcf                        : /home/dingyuanhao/zxl_software/wf-pore-c/test_data/porec_test.phased_variants.vcf.gz

Output Options
  hi_c                       : true

Advanced Options
  chunk_size                 : 100

4DN files Options
  mcool                      : true

Paired-end BAM Options
  paired_end                 : true
  paired_end_minimum_distance: 100
  paired_end_maximum_distance: 200

!! Only displaying parameters that differ from the pipeline defaults !!
--------------------------------------------------------------------------------
If you use epi2me-labs/wf-pore-c for your analysis please cite:

* The nf-core framework
  https://doi.org/10.1038/s41587-020-0439-x


--------------------------------------------------------------------------------
This is epi2me-labs/wf-pore-c v1.2.2.
--------------------------------------------------------------------------------
Searching input for [.bam, .ubam] files.
[-        ] POREC:checkBamHeaders          -
[-        ] POREC:sortBam                  -
[-        ] POREC:mergeBams                -
[-        ] POREC:catSortBams              -
[-        ] POREC:validateIndex            -
[-        ] POREC:samtools_index           -
[-        ] POREC:bamstats                 -
[-        ] POREC:index_bam                -
[-        ] POR…epare_genome:index_ref_mmi -
[-        ] POREC:digest_align_annotate    -

[-        ] POREC:checkBamHeaders          -
[-        ] POREC:sortBam                  -
[-        ] POREC:mergeBams                -
[-        ] POREC:catSortBams              -
[-        ] POREC:validateIndex            -
[-        ] POREC:samtools_index           -
[-        ] POREC:bamstats                 -
[-        ] POREC:index_bam                -
[-        ] POR…epare_genome:index_ref_mmi -
[-        ] POREC:digest_align_annotate    -
[-        ] POREC:haplotag_alignments      -
[-        ] POREC:merge_coordsorted_bams   -
[-        ] POREC:merge_namesorted_bams    -
[-        ] POREC:create_restriction_bed   -
[-        ] POREC:to_pairs_file            -
[-        ] POREC:pairsToCooler            -
[-        ] POREC:merge_mcools             -
[-        ] POREC:merge_pairs              -
[-        ] POREC:merge_pairs_stats        -
[-        ] POREC:pair_stats_report        -
Plus 8 more processes waiting for tasks…

[-        ] POREC:checkBamHeaders          | 0 of 1
[-        ] POREC:sortBam                  -
[-        ] POREC:mergeBams                -
[-        ] POREC:catSortBams              -
[-        ] POREC:validateIndex            -
[-        ] POREC:samtools_index           -
[-        ] POREC:bamstats                 -
[-        ] POREC:index_bam                -
[-        ] POR…epare_genome:index_ref_mmi -
[-        ] POREC:digest_align_annotate    -
[-        ] POREC:haplotag_alignments      -
[-        ] POREC:merge_coordsorted_bams   -
[-        ] POREC:merge_namesorted_bams    -
[-        ] POREC:create_restriction_bed   -
[-        ] POREC:to_pairs_file            -
[-        ] POREC:pairsToCooler            -
[-        ] POREC:merge_mcools             -
[-        ] POREC:merge_pairs              -
[-        ] POREC:merge_pairs_stats        -
[-        ] POREC:pair_stats_report        -
Plus 8 more processes waiting for tasks…
Pulling Singularity image docker://home/dingyuanhao/zxl_software/wf-pore-c/wf-pore-c.sif [cache /home/dingyuanhao/zxl_software/wf-pore-c/home-dingyuanhao-zxl_software-wf-pore-c-wf-pore-c.sif]

executor >  local (1)
[d5/66b39a] POREC:checkBamHeaders (1)      | 0 of 1
[-        ] POREC:sortBam                  -
[-        ] POREC:mergeBams                -
[-        ] POREC:catSortBams              -
[-        ] POREC:validateIndex            -
[-        ] POREC:samtools_index           -
[-        ] POREC:bamstats                 -
[-        ] POREC:index_bam                -
[-        ] POR…epare_genome:index_ref_mmi -
[-        ] POREC:digest_align_annotate    -
[-        ] POREC:haplotag_alignments      -
[-        ] POREC:merge_coordsorted_bams   -
[-        ] POREC:merge_namesorted_bams    -
[-        ] POREC:create_restriction_bed   -
[-        ] POREC:to_pairs_file            -
[-        ] POREC:pairsToCooler            -
[-        ] POREC:merge_mcools             -
[-        ] POREC:merge_pairs              -
[-        ] POREC:merge_pairs_stats        -
[-        ] POREC:pair_stats_report        -
Plus 8 more processes waiting for tasks…
Pulling Singularity image docker://home/dingyuanhao/zxl_software/wf-pore-c/wf-pore-c.sif [cache /home/dingyuanhao/zxl_software/wf-pore-c/home-dingyuanhao-zxl_software-wf-pore-c-wf-pore-c.sif]

executor >  local (2)
[d5/66b39a] POREC:checkBamHeaders (1)      | 1 of 1 ✔
[-        ] POREC:sortBam                  -
[-        ] POREC:mergeBams                -
[-        ] POREC:catSortBams              -
[-        ] POREC:validateIndex            -
[7e/a03742] POREC:samtools_index (1)       | 0 of 1
[-        ] POREC:bamstats                 -
[-        ] POREC:index_bam                -
[-        ] POR…epare_genome:index_ref_mmi -
[-        ] POREC:digest_align_annotate    -
[-        ] POREC:haplotag_alignments      -
[-        ] POREC:merge_coordsorted_bams   -
[-        ] POREC:merge_namesorted_bams    -
[-        ] POREC:create_restriction_bed   -
[-        ] POREC:to_pairs_file            -
[-        ] POREC:pairsToCooler            -
[-        ] POREC:merge_mcools             -
[-        ] POREC:merge_pairs              -
[-        ] POREC:merge_pairs_stats        -
[-        ] POREC:pair_stats_report        -
Plus 8 more processes waiting for tasks…
Pulling Singularity image docker://home/dingyuanhao/zxl_software/wf-pore-c/wf-pore-c.sif [cache /home/dingyuanhao/zxl_software/wf-pore-c/home-dingyuanhao-zxl_software-wf-pore-c-wf-pore-c.sif]

executor >  local (2)
[d5/66b39a] POREC:checkBamHeaders (1)      | 1 of 1 ✔
[-        ] POREC:sortBam                  -
[-        ] POREC:mergeBams                -
[-        ] POREC:catSortBams              -
[-        ] POREC:validateIndex            -
[7e/a03742] POREC:samtools_index (1)       | 1 of 1 ✔
[-        ] POREC:bamstats                 -
[-        ] POREC:index_bam                -
[-        ] POR…epare_genome:index_ref_mmi -
[-        ] POREC:digest_align_annotate    -
[-        ] POREC:haplotag_alignments      -
[-        ] POREC:merge_coordsorted_bams   -
[-        ] POREC:merge_namesorted_bams    -
[-        ] POREC:create_restriction_bed   -
[-        ] POREC:to_pairs_file            -
[-        ] POREC:pairsToCooler            -
[-        ] POREC:merge_mcools             -
[-        ] POREC:merge_pairs              -
[-        ] POREC:merge_pairs_stats        -
[-        ] POREC:pair_stats_report        -
Plus 8 more processes waiting for tasks…
Pulling Singularity image docker://home/dingyuanhao/zxl_software/wf-pore-c/wf-pore-c.sif [cache /home/dingyuanhao/zxl_software/wf-pore-c/home-dingyuanhao-zxl_software-wf-pore-c-wf-pore-c.sif]

executor >  local (3)
[d5/66b39a] POREC:checkBamHeaders (1)      | 1 of 1 ✔
[-        ] POREC:sortBam                  -
[-        ] POREC:mergeBams                -
[-        ] POREC:catSortBams              -
[-        ] POREC:validateIndex            -
[7e/a03742] POREC:samtools_index (1)       | 1 of 1 ✔
[66/2e479a] POREC:bamstats (1)             | 0 of 1
[-        ] POREC:index_bam                -
[-        ] POR…epare_genome:index_ref_mmi -
[-        ] POREC:digest_align_annotate    -
[-        ] POREC:haplotag_alignments      -
[-        ] POREC:merge_coordsorted_bams   -
[-        ] POREC:merge_namesorted_bams    -
[-        ] POREC:create_restriction_bed   -
[-        ] POREC:to_pairs_file            -
[-        ] POREC:pairsToCooler            -
[-        ] POREC:merge_mcools             -
[-        ] POREC:merge_pairs              -
[-        ] POREC:merge_pairs_stats        -
[-        ] POREC:pair_stats_report        -
Plus 8 more processes waiting for tasks…
Pulling Singularity image docker://home/dingyuanhao/zxl_software/wf-pore-c/wf-pore-c.sif [cache /home/dingyuanhao/zxl_software/wf-pore-c/home-dingyuanhao-zxl_software-wf-pore-c-wf-pore-c.sif]

executor >  local (4)
[d5/66b39a] POREC:checkBamHeaders (1)      | 1 of 1 ✔
[-        ] POREC:sortBam                  -
[-        ] POREC:mergeBams                -
[-        ] POREC:catSortBams              -
[-        ] POREC:validateIndex            -
[7e/a03742] POREC:samtools_index (1)       | 1 of 1 ✔
[66/2e479a] POREC:bamstats (1)             | 1 of 1 ✔
[-        ] POREC:index_bam                -
[-        ] POR…epare_genome:index_ref_mmi -
[-        ] POREC:digest_align_annotate    -
[-        ] POREC:haplotag_alignments      -
[-        ] POREC:merge_coordsorted_bams   -
[-        ] POREC:merge_namesorted_bams    -
[-        ] POREC:create_restriction_bed   -
[-        ] POREC:to_pairs_file            -
[-        ] POREC:pairsToCooler            -
[-        ] POREC:merge_mcools             -
[-        ] POREC:merge_pairs              -
[-        ] POREC:merge_pairs_stats        -
[-        ] POREC:pair_stats_report        -
[6c/c9e5dd] POR…ectIngressResultsInDir (1) | 0 of 1
Plus 7 more processes waiting for tasks…
Pulling Singularity image docker://home/dingyuanhao/zxl_software/wf-pore-c/wf-pore-c.sif [cache /home/dingyuanhao/zxl_software/wf-pore-c/home-dingyuanhao-zxl_software-wf-pore-c-wf-pore-c.sif]

executor >  local (4)
[d5/66b39a] POREC:checkBamHeaders (1)      | 1 of 1 ✔
[-        ] POREC:sortBam                  -
[-        ] POREC:mergeBams                -
[-        ] POREC:catSortBams              -
[-        ] POREC:validateIndex            -
[7e/a03742] POREC:samtools_index (1)       | 1 of 1 ✔
[66/2e479a] POREC:bamstats (1)             | 1 of 1 ✔
[-        ] POREC:index_bam                -
[-        ] POR…epare_genome:index_ref_mmi -
[-        ] POREC:digest_align_annotate    -
[-        ] POREC:haplotag_alignments      -
[-        ] POREC:merge_coordsorted_bams   -
[-        ] POREC:merge_namesorted_bams    -
[-        ] POREC:create_restriction_bed   -
[-        ] POREC:to_pairs_file            -
[-        ] POREC:pairsToCooler            -
[-        ] POREC:merge_mcools             -
[-        ] POREC:merge_pairs              -
[-        ] POREC:merge_pairs_stats        -
[-        ] POREC:pair_stats_report        -
[6c/c9e5dd] POR…ectIngressResultsInDir (1) | 0 of 1
Plus 7 more processes waiting for tasks…
Pulling Singularity image docker://home/dingyuanhao/zxl_software/wf-pore-c/wf-pore-c.sif [cache /home/dingyuanhao/zxl_software/wf-pore-c/home-dingyuanhao-zxl_software-wf-pore-c-wf-pore-c.sif]

executor >  local (4)
[d5/66b39a] POREC:checkBamHeaders (1)      | 1 of 1 ✔
[-        ] POREC:sortBam                  -
[-        ] POREC:mergeBams                -
[-        ] POREC:catSortBams              -
[-        ] POREC:validateIndex            -
[7e/a03742] POREC:samtools_index (1)       | 1 of 1 ✔
[66/2e479a] POREC:bamstats (1)             | 1 of 1 ✔
[-        ] POREC:index_bam                -
[-        ] POR…epare_genome:index_ref_mmi -
[-        ] POREC:digest_align_annotate    -
[-        ] POREC:haplotag_alignments      -
[-        ] POREC:merge_coordsorted_bams   -
[-        ] POREC:merge_namesorted_bams    -
[-        ] POREC:create_restriction_bed   -
[-        ] POREC:to_pairs_file            -
[-        ] POREC:pairsToCooler            -
[-        ] POREC:merge_mcools             -
[-        ] POREC:merge_pairs              -
[-        ] POREC:merge_pairs_stats        -
[-        ] POREC:pair_stats_report        -
[6c/c9e5dd] POR…ectIngressResultsInDir (1) | 1 of 1 ✔
Plus 7 more processes waiting for tasks…
Pulling Singularity image docker://home/dingyuanhao/zxl_software/wf-pore-c/wf-pore-c.sif [cache /home/dingyuanhao/zxl_software/wf-pore-c/home-dingyuanhao-zxl_software-wf-pore-c-wf-pore-c.sif]

executor >  local (4)
[d5/66b39a] POREC:checkBamHeaders (1)      | 1 of 1 ✔
[-        ] POREC:sortBam                  -
[-        ] POREC:mergeBams                -
[-        ] POREC:catSortBams              -
[-        ] POREC:validateIndex            -
[7e/a03742] POREC:samtools_index (1)       | 1 of 1 ✔
[66/2e479a] POREC:bamstats (1)             | 1 of 1 ✔
[-        ] POREC:index_bam                -
[-        ] POR…epare_genome:index_ref_mmi -
[-        ] POREC:digest_align_annotate    -
[-        ] POREC:haplotag_alignments      -
[-        ] POREC:merge_coordsorted_bams   -
[-        ] POREC:merge_namesorted_bams    -
[-        ] POREC:create_restriction_bed   -
[-        ] POREC:to_pairs_file            -
[-        ] POREC:pairsToCooler            -
[-        ] POREC:merge_mcools             -
[-        ] POREC:merge_pairs              -
[-        ] POREC:merge_pairs_stats        -
[-        ] POREC:pair_stats_report        -
[6c/c9e5dd] POR…ectIngressResultsInDir (1) | 1 of 1 ✔
Plus 7 more processes waiting for tasks…

ERROR ~ Error executing process > 'POREC:index_bam (1)'

Caused by:
  Failed to pull singularity image
    command: singularity pull  --name home-dingyuanhao-zxl_software-wf-pore-c-wf-pore-c.sif.pulling.1729494354443 docker://home/dingyuanhao/zxl_software/wf-pore-c/wf-pore-c.sif > /dev/null
    status : 255
    hint   : Try and increase singularity.pullTimeout in the config (current is "20m")
    message:
      [31mFATAL:   While making image from oci registry: failed to get checksum for docker://home/dingyuanhao/zxl_software/wf-pore-c/wf-pore-c.sif: pinging docker registry returned: Get "https://registry-1.docker.io/v2/": dial tcp 103.200.30.143:443: i/o timeout



 -- Check '.nextflow.log' file for details

executor >  local (4)
[d5/66b39a] POREC:checkBamHeaders (1)      | 1 of 1 ✔
[-        ] POREC:sortBam                  -
[-        ] POREC:mergeBams                -
[-        ] POREC:catSortBams              -
[-        ] POREC:validateIndex            -
[7e/a03742] POREC:samtools_index (1)       | 1 of 1 ✔
[66/2e479a] POREC:bamstats (1)             | 1 of 1 ✔
[-        ] POREC:index_bam                -
[-        ] POR…epare_genome:index_ref_mmi -
[-        ] POREC:digest_align_annotate    -
[-        ] POREC:haplotag_alignments      -
[-        ] POREC:merge_coordsorted_bams   -
[-        ] POREC:merge_namesorted_bams    -
[-        ] POREC:create_restriction_bed   -
[-        ] POREC:to_pairs_file            -
[-        ] POREC:pairsToCooler            -
[-        ] POREC:merge_mcools             -
[-        ] POREC:merge_pairs              -
[-        ] POREC:merge_pairs_stats        -
[-        ] POREC:pair_stats_report        -
[6c/c9e5dd] POR…ectIngressResultsInDir (1) | 1 of 1 ✔
Plus 7 more processes waiting for tasks…
ERROR ~ Error executing process > 'POREC:index_bam (1)'

Caused by:
  Failed to pull singularity image
    command: singularity pull  --name home-dingyuanhao-zxl_software-wf-pore-c-wf-pore-c.sif.pulling.1729494354443 docker://home/dingyuanhao/zxl_software/wf-pore-c/wf-pore-c.sif > /dev/null
    status : 255
    hint   : Try and increase singularity.pullTimeout in the config (current is "20m")
    message:
      [31mFATAL:   While making image from oci registry: failed to get checksum for docker://home/dingyuanhao/zxl_software/wf-pore-c/wf-pore-c.sif: pinging docker registry returned: Get "https://registry-1.docker.io/v2/": dial tcp 103.200.30.143:443: i/o timeout



 -- Check '.nextflow.log' file for details
```

### Were you able to successfully run the latest version of the workflow with the demo data?

yes

**Comment by Blosers** [comment]
I think I have already configured local running in the NextFlow.dentig file, but why is the network still being pulled? Is there any problem with my offline running configuration in the NextFlow.dentig file?

**Comment by sarahjeeeze** [comment]
Heym did you first set environemnt variable with  `export NXF_OFFLINE='true'`

**Comment by Blosers** [comment]
I still want to ask if I should write it in my. bahsrc file or in the Nextflow.comntig file. Thank you very much for your reply.

**Comment by SamStudio8** [comment]
Export statements such as this should go in your bash environment. For support running Nextflow offline I suggest the Nextflow community https://community.seqera.io/
