### ISSUE TITLE
demo data request

### ISSUE THREAD

**Issue by biozzq** [epi2me-labs/wf-pore-c#84]
Hi，

Could you please let me know if there are any available raw signal data (.pod5) that I could use for practice? I am eager to see how well the process handles this issue (https://github.com/nanoporetech/modkit/issues/289), and having access to such data would be immensely helpful.

Thank you very much for your assistance!

Best regards,
Zheng zhuqing

**Comment by biozzq** [comment]
Dear @sarahjeeeze 

Thank you. I found the Pore-C base calling BAM file (PAW44788.bam, size 88G) on the website you shared. However, I am looking for a smaller Pod5 file that I can use just for testing. I would like to start from base calling and complete the whole processing workflow (assess the methylation information for Pore-C data).

Additionally, if you could provide a reference result file to use for comparison, it would be really helpful for checking the accuracy of my workflow.

Thank you very much for your help!

Best wishes,
zheng zhuqing

**Comment by SamStudio8** [comment]
Hi @biozzq - we only have the data on the EPI2ME Labs website to offer.
